"""Tests for Claude memory emission (compiler/memory_emit.py)."""
from __future__ import annotations

from pathlib import Path

from holoctl.lib.compiler import memory_emit
from holoctl.lib.compiler.manifest import CompileLedger
from holoctl.lib.memory import Memory


def _ledger(tmp_path: Path) -> CompileLedger:
    """A target-scoped ledger like the one the compiler builds per run."""
    return CompileLedger(tmp_path, target="claude")


def _seed(tmp_path: Path) -> Memory:
    mem = Memory(tmp_path)
    mem.ensure_seed("TestProj")
    mem.ensure_gitignore()
    mem.add_topic(
        "decisions",
        body="2026-05-04 chose stdio over HTTP daemon for MCP.",
        scope="lazy",
        description="Architectural decisions log",
    )
    mem.add_topic(
        "api-conventions",
        body="REST endpoints use kebab-case in paths.",
        scope="glob",
        globs=["src/api/**", "tests/api/**"],
    )
    mem.add_topic(
        "always-rules",
        body="Never log credentials.",
        scope="always_on",
    )
    return mem


def test_emit_claude_writes_index_and_topic_skills(tmp_path: Path):
    _seed(tmp_path)
    paths = memory_emit.emit_claude(tmp_path, _ledger(tmp_path))
    paths_set = set(paths)
    assert ".claude/skills/holoctl-memory/SKILL.md" in paths_set
    assert ".claude/skills/holoctl-memory-decisions/SKILL.md" in paths_set
    assert ".claude/skills/holoctl-memory-api-conventions/SKILL.md" in paths_set
    assert ".claude/skills/holoctl-memory-always-rules/SKILL.md" in paths_set


def test_emit_claude_lazy_topic_has_description(tmp_path: Path):
    _seed(tmp_path)
    memory_emit.emit_claude(tmp_path, _ledger(tmp_path))
    body = (
        tmp_path / ".claude/skills/holoctl-memory-decisions/SKILL.md"
    ).read_text(encoding="utf-8")
    assert "name: holoctl-memory-decisions" in body
    assert "Architectural decisions log" in body


def test_emit_claude_glob_topic_has_paths(tmp_path: Path):
    _seed(tmp_path)
    memory_emit.emit_claude(tmp_path, _ledger(tmp_path))
    body = (
        tmp_path / ".claude/skills/holoctl-memory-api-conventions/SKILL.md"
    ).read_text(encoding="utf-8")
    assert "paths:" in body
    assert "src/api/**" in body


def test_emit_claude_output_is_headerless(tmp_path: Path):
    """Manifest replaces the header: emitted SKILL.md must NOT carry it."""
    _seed(tmp_path)
    memory_emit.emit_claude(tmp_path, _ledger(tmp_path))
    index = (
        tmp_path / ".claude/skills/holoctl-memory/SKILL.md"
    ).read_text(encoding="utf-8")
    assert "Generated by holoctl" not in index
    # Frontmatter is still the first thing in the file.
    assert index.startswith("---\nname: holoctl-memory\n")


def test_emit_no_memory_dir_returns_empty(tmp_path: Path):
    """The compiler must be tolerant of workspaces without memory yet."""
    assert memory_emit.emit_claude(tmp_path, _ledger(tmp_path)) == []


def test_claude_memory_reference_block_mentions_index_and_cli():
    block = memory_emit.claude_memory_reference_block()
    assert "@.holoctl/memory/MEMORY.md" in block
    assert "hctl memory" in block
