"""Tests for M9/M11 — defense against overwriting hand-edited compile outputs.

Post-manifest model (header retired):
- M9: `.claude/agents/*` and `.claude/commands/*` outputs are tracked in the
  manifest. A file that holoctl owns-unmodified is overwritten on recompile; one
  the user hand-edited (hash drifted from the manifest) or a foreign file (never
  in the manifest) is preserved.
- M11: CLAUDE.md gets defensive treatment — genuinely hand-edited content is
  preserved via rename to `CLAUDE.local.md` (not just skipped).
- `--force` (via HOLOCTL_COMPILE_FORCE env, read by the self-owned ledger)
  bypasses the check; CLAUDE.md gets a `.claude/.cache/CLAUDE.backup-<ts>.md`
  backup before overwrite.

These call `compile_claude` directly (no orchestrator), so it builds and
finalizes its own target-scoped ledger.
"""
from __future__ import annotations
import os
from pathlib import Path

import pytest

from holoctl.lib.compiler.claude import compile_claude


@pytest.fixture(autouse=True)
def _clear_force_env():
    """Ensure no test pollutes the env force flag for another."""
    os.environ.pop("HOLOCTL_COMPILE_FORCE", None)
    yield
    os.environ.pop("HOLOCTL_COMPILE_FORCE", None)


def _seed_minimal_holoctl(root: Path) -> None:
    """Minimal .holoctl/ tree so compile_claude has something to emit."""
    (root / ".holoctl").mkdir()
    (root / ".holoctl" / "instructions.md").write_text(
        "# Project\n\nminimal seed.\n", encoding="utf-8"
    )
    # An agent + a command so we can test the skip behavior.
    (root / ".holoctl" / "agents").mkdir()
    (root / ".holoctl" / "agents" / "boardmaster.md").write_text(
        "---\nname: boardmaster\ndescription: test\n---\n\nbody\n", encoding="utf-8"
    )
    (root / ".holoctl" / "commands").mkdir()
    (root / ".holoctl" / "commands" / "status.md").write_text(
        "---\nname: status\n---\n\nstatus body\n", encoding="utf-8"
    )


def _config() -> dict:
    from holoctl.lib.config import get_defaults
    cfg = get_defaults()
    cfg["project"]["name"] = "TestProject"
    cfg["project"]["prefix"] = "TST"
    return cfg


def test_claude_md_first_time_writes_clean_and_tracked(tmp_path: Path):
    _seed_minimal_holoctl(tmp_path)
    compile_claude(tmp_path, _config())
    claude_md = tmp_path / "CLAUDE.md"
    assert claude_md.exists()
    # Headerless: no generated marker anywhere.
    assert "Generated by holoctl" not in claude_md.read_text(encoding="utf-8")
    # Tracked in the manifest.
    from holoctl.lib.compiler.manifest import load
    assert "CLAUDE.md" in load(tmp_path)["files"]


def test_claude_md_preserves_hand_edited_via_rename(tmp_path: Path):
    """Pre-existing foreign CLAUDE.md (not in manifest) → moved to CLAUDE.local.md."""
    _seed_minimal_holoctl(tmp_path)
    handwritten = "# My carefully crafted CLAUDE.md\n\nThis took hours.\n"
    (tmp_path / "CLAUDE.md").write_text(handwritten, encoding="utf-8")

    result = compile_claude(tmp_path, _config())

    local = tmp_path / "CLAUDE.local.md"
    assert local.exists()
    assert local.read_text(encoding="utf-8") == handwritten

    new_claude = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert "carefully crafted" not in new_claude

    # Skipped report mentions the preservation.
    assert any(
        "CLAUDE.local.md" in s.get("reason", "")
        for s in result.get("skipped", [])
    )


def test_claude_md_overwrites_when_owned(tmp_path: Path):
    """A previously-compiled (manifest-tracked, unmodified) CLAUDE.md is overwritten."""
    _seed_minimal_holoctl(tmp_path)
    compile_claude(tmp_path, _config())  # first compile records it

    # Change the source, recompile — owned file is regenerated, no .local.md.
    (tmp_path / ".holoctl" / "instructions.md").write_text(
        "# Project\n\nUPDATED seed.\n", encoding="utf-8"
    )
    compile_claude(tmp_path, _config())
    new = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert "UPDATED seed." in new
    assert not (tmp_path / "CLAUDE.local.md").exists()


def test_claude_md_adopts_legacy_headered_file(tmp_path: Path):
    """A legacy headered CLAUDE.md (not in manifest) is adopted → clean + tracked."""
    _seed_minimal_holoctl(tmp_path)
    (tmp_path / "CLAUDE.md").write_text(
        "<!-- Generated by holoctl. Do not edit directly. -->\n\nold content\n",
        encoding="utf-8",
    )
    compile_claude(tmp_path, _config())
    new = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert "old content" not in new
    assert "Generated by holoctl" not in new
    assert not (tmp_path / "CLAUDE.local.md").exists()
    from holoctl.lib.compiler.manifest import load
    assert "CLAUDE.md" in load(tmp_path)["files"]


def test_claude_md_force_backs_up_and_overwrites(tmp_path: Path):
    """With --force, hand-edited CLAUDE.md is backed up to .claude/.cache/ then overwritten."""
    _seed_minimal_holoctl(tmp_path)
    handwritten = "# Hand-edited\n\nimportant content\n"
    (tmp_path / "CLAUDE.md").write_text(handwritten, encoding="utf-8")

    os.environ["HOLOCTL_COMPILE_FORCE"] = "1"
    compile_claude(tmp_path, _config())

    new = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert "Generated by holoctl" not in new
    assert "Hand-edited" not in new

    # Backup exists in .claude/.cache/
    backups = list((tmp_path / ".claude" / ".cache").glob("CLAUDE.backup-*.md"))
    assert len(backups) == 1
    assert backups[0].read_text(encoding="utf-8") == handwritten


def test_claude_md_rename_avoids_clobbering_existing_local(tmp_path: Path):
    """If CLAUDE.local.md already exists, use a timestamped variant."""
    _seed_minimal_holoctl(tmp_path)
    (tmp_path / "CLAUDE.md").write_text("# Hand-edited v2\n", encoding="utf-8")
    (tmp_path / "CLAUDE.local.md").write_text("# Hand-edited v1\n", encoding="utf-8")

    compile_claude(tmp_path, _config())

    # Original CLAUDE.local.md preserved.
    assert "# Hand-edited v1" in (tmp_path / "CLAUDE.local.md").read_text(encoding="utf-8")
    # The newer hand-edit is in a timestamped local.
    timestamped = [
        p for p in tmp_path.glob("CLAUDE.local.*.md")
    ]
    assert len(timestamped) == 1
    assert "# Hand-edited v2" in timestamped[0].read_text(encoding="utf-8")


def test_agent_file_hand_edited_is_skipped(tmp_path: Path):
    """M9: hand-edited .claude/agents/<name>.md (manifest hash drifted) is preserved."""
    _seed_minimal_holoctl(tmp_path)
    # First compile creates the file + records it in the manifest.
    compile_claude(tmp_path, _config())
    bm_path = tmp_path / ".claude" / "agents" / "boardmaster.md"
    assert bm_path.exists()
    # Headerless.
    assert "Generated by holoctl" not in bm_path.read_text(encoding="utf-8")

    # Simulate user editing content (hash now drifts from the manifest).
    bm_path.write_text(
        "---\nname: boardmaster\n---\n\n# My custom boardmaster\n",
        encoding="utf-8",
    )

    # Modify the source to force a real change attempt.
    (tmp_path / ".holoctl" / "agents" / "boardmaster.md").write_text(
        "---\nname: boardmaster\ndescription: changed\n---\n\nnew body\n",
        encoding="utf-8",
    )

    result = compile_claude(tmp_path, _config())

    # The hand-edited content survives.
    surviving = bm_path.read_text(encoding="utf-8")
    assert "My custom boardmaster" in surviving
    assert "new body" not in surviving

    # Skipped is reported.
    skip_paths = [s["path"] for s in result.get("skipped", [])]
    assert any("boardmaster.md" in p for p in skip_paths)


def test_agent_file_force_overwrites(tmp_path: Path):
    """M9: --force bypasses skip and overwrites hand-edited agent file."""
    _seed_minimal_holoctl(tmp_path)
    compile_claude(tmp_path, _config())
    bm_path = tmp_path / ".claude" / "agents" / "boardmaster.md"
    bm_path.write_text("# hand-edited\n", encoding="utf-8")

    (tmp_path / ".holoctl" / "agents" / "boardmaster.md").write_text(
        "---\nname: boardmaster\ndescription: changed\n---\n\nfresh body\n",
        encoding="utf-8",
    )

    os.environ["HOLOCTL_COMPILE_FORCE"] = "1"
    compile_claude(tmp_path, _config())

    after = bm_path.read_text(encoding="utf-8")
    assert "Generated by holoctl" not in after
    assert "# hand-edited" not in after
    assert "fresh body" in after
