"""Integration: header→manifest migration end-to-end.

Locks the four headline behaviors of routing the compiler onto the manifest:

  1. compile → outputs are headerless and `.holoctl/.compiled.json` lists them
  2. remove an agent source + recompile → its `.claude/agents/<x>.md` is pruned
     and the manifest no longer lists it
  3. a hand-edited (headerless, not-in-manifest) foreign `.claude/agents/foo.md`
     is preserved across recompile
  4. a legacy headered file is migrated to clean + tracked on first compile
"""
from __future__ import annotations

from pathlib import Path

from holoctl.lib.compiler import compile_project
from holoctl.lib.compiler.manifest import load, manifest_path
from holoctl.lib.config import get_defaults


def _seed(root: Path) -> dict:
    holoctl = root / ".holoctl"
    (holoctl / "agents").mkdir(parents=True, exist_ok=True)
    (holoctl / "commands").mkdir(parents=True, exist_ok=True)
    (holoctl / "context").mkdir(parents=True, exist_ok=True)
    (holoctl / "agents" / "boardmaster.md").write_text(
        "---\nname: boardmaster\ndescription: bm\n---\n# bm body\n", encoding="utf-8"
    )
    (holoctl / "agents" / "dev.md").write_text(
        "---\nname: dev\ndescription: dev\n---\n# dev body\n", encoding="utf-8"
    )
    (holoctl / "commands" / "status.md").write_text(
        "---\nname: status\ndescription: st\n---\n# status body\n", encoding="utf-8"
    )
    (holoctl / "instructions.md").write_text(
        "# Project\n\nseed.\n", encoding="utf-8"
    )
    (holoctl / "context" / "objective.md").write_text("obj.\n", encoding="utf-8")
    return get_defaults()


def test_outputs_headerless_and_manifest_lists_them(tmp_path: Path):
    config = _seed(tmp_path)
    result = compile_project(tmp_path, config, "claude", force=False)

    # Every emitted markdown file is clean (no header).
    for rel in result["files"]:
        p = tmp_path / rel
        if p.suffix == ".md":
            assert "Generated by holoctl" not in p.read_text(encoding="utf-8"), rel

    # Manifest exists and tracks the agent + command + CLAUDE.md.
    assert manifest_path(tmp_path).exists()
    tracked = load(tmp_path)["files"]
    assert ".claude/agents/boardmaster.md" in tracked
    assert ".claude/agents/dev.md" in tracked
    assert ".claude/commands/status.md" in tracked
    assert "CLAUDE.md" in tracked
    # Each entry carries its source + target.
    assert tracked[".claude/agents/dev.md"]["target"] == "claude"
    assert tracked[".claude/agents/dev.md"]["source"] == ".holoctl/agents/dev.md"


def test_removing_agent_source_prunes_output_and_manifest(tmp_path: Path):
    config = _seed(tmp_path)
    compile_project(tmp_path, config, "claude")
    dev_out = tmp_path / ".claude" / "agents" / "dev.md"
    assert dev_out.exists()
    assert ".claude/agents/dev.md" in load(tmp_path)["files"]

    # Remove the source agent and recompile.
    (tmp_path / ".holoctl" / "agents" / "dev.md").unlink()
    result = compile_project(tmp_path, config, "claude")

    # Output pruned, manifest no longer lists it, prune reported.
    assert not dev_out.exists()
    assert ".claude/agents/dev.md" not in load(tmp_path)["files"]
    assert ".claude/agents/dev.md" in result["removed"]
    # The surviving agent is untouched.
    assert (tmp_path / ".claude" / "agents" / "boardmaster.md").exists()


def test_foreign_agent_file_is_preserved(tmp_path: Path):
    config = _seed(tmp_path)
    compile_project(tmp_path, config, "claude")

    # A headerless file holoctl never generated (not in the manifest).
    foreign = tmp_path / ".claude" / "agents" / "foo.md"
    foreign.write_text("# my own subagent\n", encoding="utf-8")

    result = compile_project(tmp_path, config, "claude")

    # Preserved (it's not a holoctl source, so it's neither pruned nor clobbered).
    assert foreign.read_text(encoding="utf-8") == "# my own subagent\n"
    assert ".claude/agents/foo.md" not in load(tmp_path)["files"]
    # It was never in prev, so prune leaves it entirely alone (no removed entry).
    assert ".claude/agents/foo.md" not in result["removed"]


def test_legacy_headered_file_is_migrated(tmp_path: Path):
    config = _seed(tmp_path)

    # Plant a legacy headered output as if a pre-manifest compile produced it.
    legacy = tmp_path / ".claude" / "agents" / "boardmaster.md"
    legacy.parent.mkdir(parents=True, exist_ok=True)
    legacy.write_text(
        "<!-- Generated by holoctl. Do not edit directly. Source: .holoctl/ -->\n\n"
        "---\nname: boardmaster\n---\nstale body\n",
        encoding="utf-8",
    )

    result = compile_project(tmp_path, config, "claude")

    # Adopted: clean content, tracked, reported as migrated.
    after = legacy.read_text(encoding="utf-8")
    assert "Generated by holoctl" not in after
    assert "stale body" not in after
    assert ".claude/agents/boardmaster.md" in load(tmp_path)["files"]
    assert ".claude/agents/boardmaster.md" in result["migrated"]


def test_hand_edited_managed_agent_keeps_manifest_entry_single_skip(tmp_path: Path):
    """Hand-editing a MANAGED agent and recompiling must:
    (a) keep its manifest entry (with the PRE-edit hash) so drift can label it
        hand-edited rather than stale;
    (b) emit exactly ONE skip note for it (write's skip, not a duplicate from
        prune_orphans).
    """
    config = _seed(tmp_path)
    compile_project(tmp_path, config, "claude")

    dev_out = tmp_path / ".claude" / "agents" / "dev.md"
    assert dev_out.exists()
    pre_edit_hash = load(tmp_path)["files"][".claude/agents/dev.md"]["sha256"]

    # Hand-edit the managed output (it's owned, now diverges from the manifest).
    dev_out.write_text("# hand-edited by the user\n", encoding="utf-8")

    result = compile_project(tmp_path, config, "claude")

    # (a) Manifest still records dev.md, carrying the OLD (pre-edit) hash.
    tracked = load(tmp_path)["files"]
    assert ".claude/agents/dev.md" in tracked
    assert tracked[".claude/agents/dev.md"]["sha256"] == pre_edit_hash

    # The hand-edit on disk is preserved (not clobbered, not pruned).
    assert dev_out.read_text(encoding="utf-8") == "# hand-edited by the user\n"
    assert ".claude/agents/dev.md" not in result["removed"]

    # (b) Exactly ONE skip note for dev.md (no duplicate from prune_orphans).
    dev_notes = [s for s in result["skipped"] if s["path"] == ".claude/agents/dev.md"]
    assert len(dev_notes) == 1, dev_notes
    assert "hand-edited" in dev_notes[0]["reason"]


def test_foreign_file_still_unrecorded_and_preserved(tmp_path: Path):
    """A genuinely foreign file (never in prev) is NOT recorded in the manifest
    and is preserved — the carry-forward must not leak to foreign files."""
    config = _seed(tmp_path)
    compile_project(tmp_path, config, "claude")

    foreign = tmp_path / ".claude" / "agents" / "stranger.md"
    foreign.write_text("# not holoctl's\n", encoding="utf-8")

    result = compile_project(tmp_path, config, "claude")

    assert foreign.read_text(encoding="utf-8") == "# not holoctl's\n"
    assert ".claude/agents/stranger.md" not in load(tmp_path)["files"]
    assert ".claude/agents/stranger.md" not in result["removed"]


def test_hand_edit_no_other_changes_avoids_manifest_churn(tmp_path: Path):
    """Carrying prev[rel] forward unchanged keeps merged==prev when nothing else
    changed → finalize skips the rewrite (mtime preserved)."""
    config = _seed(tmp_path)
    compile_project(tmp_path, config, "claude")

    mp = manifest_path(tmp_path)
    mtime_before = mp.stat().st_mtime_ns

    # Hand-edit a managed agent, then recompile. Only this file diverges; all
    # other managed outputs stay owned-unmodified → merged should equal prev.
    (tmp_path / ".claude" / "agents" / "dev.md").write_text(
        "# hand-edited\n", encoding="utf-8"
    )
    compile_project(tmp_path, config, "claude")

    assert mp.stat().st_mtime_ns == mtime_before, "manifest rewritten despite no change"


def test_multi_target_manifest_keeps_both(tmp_path: Path):
    """Compiling claude then agents must leave BOTH targets' entries in the manifest
    (the merge-preserving finalize), and prune must not cross targets."""
    config = _seed(tmp_path)
    compile_project(tmp_path, config, "claude")
    compile_project(tmp_path, config, "agents")

    tracked = load(tmp_path)["files"]
    # claude side survived the agents compile.
    assert ".claude/agents/boardmaster.md" in tracked
    assert "CLAUDE.md" in tracked
    # agents side present.
    assert "AGENTS.md" in tracked
    assert tracked["AGENTS.md"]["target"] == "agents"
    # Claude outputs were not pruned by the agents run.
    assert (tmp_path / ".claude" / "agents" / "boardmaster.md").exists()
