"""F4 — the hand-edit guard now protects every markdown target, not just Claude.

Before this, only `compile_claude` checked for the holoctl header before
overwriting. `agents` / `copilot` / `codex` wrote blindly, so a user's
hand-edited `AGENTS.md` / `.github/copilot-instructions.md` /
`.codex/AGENTS.override.md` was silently clobbered on recompile — directly
contradicting the "never overwrite hand-edited AI configs" rule holoctl itself
ships in the generated `AGENTS.md`.
"""
from __future__ import annotations

import os
from pathlib import Path

import pytest

from holoctl.lib.compiler.agents import compile_agents
from holoctl.lib.compiler.codex import compile_codex
from holoctl.lib.compiler.copilot import compile_copilot
from holoctl.lib.config import get_defaults


@pytest.fixture(autouse=True)
def _clear_force_env():
    os.environ.pop("HOLOCTL_COMPILE_FORCE", None)
    yield
    os.environ.pop("HOLOCTL_COMPILE_FORCE", None)


def _seed(root: Path) -> None:
    (root / ".holoctl" / "context").mkdir(parents=True, exist_ok=True)
    (root / ".holoctl" / "instructions.md").write_text(
        "# Project\n\nseed instructions.\n", encoding="utf-8"
    )
    (root / ".holoctl" / "context" / "objective.md").write_text(
        "Do the thing.\n", encoding="utf-8"
    )


def _config() -> dict:
    cfg = get_defaults()
    cfg["project"]["name"] = "Drift"
    cfg["project"]["prefix"] = "DR"
    return cfg


# (compiler, output rel path)
_CASES = [
    (compile_agents, "AGENTS.md"),
    (compile_copilot, ".github/copilot-instructions.md"),
    (compile_codex, ".codex/AGENTS.override.md"),
]


@pytest.mark.parametrize("compiler,out_rel", _CASES)
def test_first_compile_writes_with_header(tmp_path: Path, compiler, out_rel: str):
    _seed(tmp_path)
    compiler(tmp_path, _config())
    out = tmp_path / out_rel
    assert out.exists()
    assert "<!-- Generated by holoctl" in out.read_text(encoding="utf-8")[:200]


@pytest.mark.parametrize("compiler,out_rel", _CASES)
def test_hand_edited_output_is_preserved(tmp_path: Path, compiler, out_rel: str):
    _seed(tmp_path)
    compiler(tmp_path, _config())
    out = tmp_path / out_rel

    # User strips the header and edits.
    out.write_text("# Hand-edited\n\nDo not clobber me.\n", encoding="utf-8")
    # Change the source so a naive compiler would rewrite.
    (tmp_path / ".holoctl" / "instructions.md").write_text(
        "# Project\n\nCHANGED source.\n", encoding="utf-8"
    )

    result = compiler(tmp_path, _config())

    surviving = out.read_text(encoding="utf-8")
    assert "Do not clobber me." in surviving
    assert "CHANGED source." not in surviving
    skip_paths = [s["path"] for s in result.get("skipped", [])]
    assert any(out_rel.split("/")[-1] in p for p in skip_paths), result


@pytest.mark.parametrize("compiler,out_rel", _CASES)
def test_force_overwrites_hand_edited_output(tmp_path: Path, compiler, out_rel: str):
    _seed(tmp_path)
    compiler(tmp_path, _config())
    out = tmp_path / out_rel
    out.write_text("# Hand-edited no header\n", encoding="utf-8")

    os.environ["HOLOCTL_COMPILE_FORCE"] = "1"
    compiler(tmp_path, _config())

    after = out.read_text(encoding="utf-8")
    assert "<!-- Generated by holoctl" in after[:200]
    assert "Hand-edited no header" not in after
