"""Tests for M9/M11 — defense against overwriting hand-edited compile outputs.

- M9: skip writing `.claude/agents/*` and `.claude/commands/*` files that look
  hand-edited (no `<!-- Generated by holoctl -->` header).
- M11: CLAUDE.md gets defensive treatment — hand-edited content is preserved
  via rename to `CLAUDE.local.md` (not just skipped).
- `--force` (via HOLOCTL_COMPILE_FORCE env) bypasses the check; CLAUDE.md
  gets a `.claude/.cache/CLAUDE.backup-<ts>.md` backup before overwrite.
"""
from __future__ import annotations
import os
from pathlib import Path

import pytest

from holoctl.lib.compiler.claude import compile_claude


@pytest.fixture(autouse=True)
def _clear_force_env():
    """Ensure no test pollutes the env force flag for another."""
    os.environ.pop("HOLOCTL_COMPILE_FORCE", None)
    yield
    os.environ.pop("HOLOCTL_COMPILE_FORCE", None)


def _seed_minimal_holoctl(root: Path) -> None:
    """Minimal .holoctl/ tree so compile_claude has something to emit."""
    (root / ".holoctl").mkdir()
    (root / ".holoctl" / "instructions.md").write_text(
        "# Project\n\nminimal seed.\n", encoding="utf-8"
    )
    # An agent + a command so we can test the skip behavior.
    (root / ".holoctl" / "agents").mkdir()
    (root / ".holoctl" / "agents" / "boardmaster.md").write_text(
        "---\nname: boardmaster\ndescription: test\n---\n\nbody\n", encoding="utf-8"
    )
    (root / ".holoctl" / "commands").mkdir()
    (root / ".holoctl" / "commands" / "status.md").write_text(
        "---\nname: status\n---\n\nstatus body\n", encoding="utf-8"
    )


def _config() -> dict:
    from holoctl.lib.config import get_defaults
    cfg = get_defaults()
    cfg["project"]["name"] = "TestProject"
    cfg["project"]["prefix"] = "TST"
    return cfg


def test_claude_md_first_time_writes_with_header(tmp_path: Path):
    _seed_minimal_holoctl(tmp_path)
    compile_claude(tmp_path, _config())
    claude_md = tmp_path / "CLAUDE.md"
    assert claude_md.exists()
    assert "<!-- Generated by holoctl" in claude_md.read_text(encoding="utf-8")[:200]


def test_claude_md_preserves_hand_edited_via_rename(tmp_path: Path):
    """Pre-existing CLAUDE.md without holoctl header → moved to CLAUDE.local.md."""
    _seed_minimal_holoctl(tmp_path)
    handwritten = "# My carefully crafted CLAUDE.md\n\nThis took hours.\n"
    (tmp_path / "CLAUDE.md").write_text(handwritten, encoding="utf-8")

    result = compile_claude(tmp_path, _config())

    local = tmp_path / "CLAUDE.local.md"
    assert local.exists()
    assert local.read_text(encoding="utf-8") == handwritten

    new_claude = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert "<!-- Generated by holoctl" in new_claude
    assert "carefully crafted" not in new_claude

    # Skipped report mentions the preservation.
    assert any(
        "CLAUDE.local.md" in s.get("reason", "")
        for s in result.get("skipped", [])
    )


def test_claude_md_overwrites_when_holoctl_header_present(tmp_path: Path):
    """If existing CLAUDE.md has the holoctl header, treat as generated and overwrite."""
    _seed_minimal_holoctl(tmp_path)
    (tmp_path / "CLAUDE.md").write_text(
        "<!-- Generated by holoctl. Do not edit directly. -->\n\nold content\n",
        encoding="utf-8",
    )
    compile_claude(tmp_path, _config())
    new = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert "old content" not in new
    assert "<!-- Generated by holoctl" in new
    # No .local.md should be created.
    assert not (tmp_path / "CLAUDE.local.md").exists()


def test_claude_md_force_backs_up_and_overwrites(tmp_path: Path):
    """With --force, hand-edited CLAUDE.md is backed up to .claude/.cache/ then overwritten."""
    _seed_minimal_holoctl(tmp_path)
    handwritten = "# Hand-edited\n\nimportant content\n"
    (tmp_path / "CLAUDE.md").write_text(handwritten, encoding="utf-8")

    os.environ["HOLOCTL_COMPILE_FORCE"] = "1"
    compile_claude(tmp_path, _config())

    new = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert "<!-- Generated by holoctl" in new
    assert "Hand-edited" not in new

    # Backup exists in .claude/.cache/
    backups = list((tmp_path / ".claude" / ".cache").glob("CLAUDE.backup-*.md"))
    assert len(backups) == 1
    assert backups[0].read_text(encoding="utf-8") == handwritten


def test_claude_md_rename_avoids_clobbering_existing_local(tmp_path: Path):
    """If CLAUDE.local.md already exists, use a timestamped variant."""
    _seed_minimal_holoctl(tmp_path)
    (tmp_path / "CLAUDE.md").write_text("# Hand-edited v2\n", encoding="utf-8")
    (tmp_path / "CLAUDE.local.md").write_text("# Hand-edited v1\n", encoding="utf-8")

    compile_claude(tmp_path, _config())

    # Original CLAUDE.local.md preserved.
    assert "# Hand-edited v1" in (tmp_path / "CLAUDE.local.md").read_text(encoding="utf-8")
    # The newer hand-edit is in a timestamped local.
    timestamped = [
        p for p in tmp_path.glob("CLAUDE.local.*.md")
    ]
    assert len(timestamped) == 1
    assert "# Hand-edited v2" in timestamped[0].read_text(encoding="utf-8")


def test_agent_file_hand_edited_is_skipped(tmp_path: Path):
    """M9: hand-edited .claude/agents/<name>.md (no header) is preserved."""
    _seed_minimal_holoctl(tmp_path)
    # First compile creates the file with header.
    compile_claude(tmp_path, _config())
    bm_path = tmp_path / ".claude" / "agents" / "boardmaster.md"
    assert bm_path.exists()

    # Simulate user removing the header and editing content.
    bm_path.write_text(
        "---\nname: boardmaster\n---\n\n# My custom boardmaster\n",
        encoding="utf-8",
    )

    # Modify the source to force a real change attempt.
    (tmp_path / ".holoctl" / "agents" / "boardmaster.md").write_text(
        "---\nname: boardmaster\ndescription: changed\n---\n\nnew body\n",
        encoding="utf-8",
    )

    result = compile_claude(tmp_path, _config())

    # The hand-edited content survives.
    surviving = bm_path.read_text(encoding="utf-8")
    assert "My custom boardmaster" in surviving
    assert "new body" not in surviving

    # Skipped is reported.
    skip_paths = [s["path"] for s in result.get("skipped", [])]
    assert any("boardmaster.md" in p for p in skip_paths)


def test_agent_file_force_overwrites(tmp_path: Path):
    """M9: --force bypasses skip and overwrites hand-edited agent file."""
    _seed_minimal_holoctl(tmp_path)
    compile_claude(tmp_path, _config())
    bm_path = tmp_path / ".claude" / "agents" / "boardmaster.md"
    bm_path.write_text("# hand-edited no header\n", encoding="utf-8")

    (tmp_path / ".holoctl" / "agents" / "boardmaster.md").write_text(
        "---\nname: boardmaster\ndescription: changed\n---\n\nfresh body\n",
        encoding="utf-8",
    )

    os.environ["HOLOCTL_COMPILE_FORCE"] = "1"
    compile_claude(tmp_path, _config())

    after = bm_path.read_text(encoding="utf-8")
    assert "<!-- Generated by holoctl" in after
    assert "hand-edited no header" not in after
    assert "fresh body" in after
