"""Wave-2 item 5.1 — init templates moved from Python f-strings to disk files.

Golden guarantee: the output of ``get_templates()`` (and therefore ``hctl
init``) must be **byte-identical** to the old embedded-f-string implementation.
The hashes below were generated by running the OLD ``holoctl/lib/templates.py``
at origin/main (commit 9090943, v0.21.0) against the same configs:

    sha256(get_templates(cfg)[key].encode("utf-8")).hexdigest()

If a template is *deliberately* changed later, regenerate the affected hash
with the snippet above and update it here in the same commit — that is the
point of this pin: template content changes must be explicit, never an
accident of the disk-loading/placeholder mechanics.
"""
from __future__ import annotations

import hashlib
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

import pytest

from holoctl.lib.config import get_defaults
from holoctl.lib.templates import _TEMPLATE_SOURCES, get_templates

# ---------------------------------------------------------------------------
# Snapshot 1 — default config (what a bare `hctl init` materializes).
# ---------------------------------------------------------------------------
GOLDEN_DEFAULT = {
    ".holoctl/agents/boardmaster.md": "10b2e25a0622cfa602337fca74fe75f8e42d8d4db5b60702bbfd9533683cb6b8",
    ".holoctl/board/WORKFLOW.md": "cf052c7f326a89b7a616c20892d8ceb73edb0a0bf65553f8c104af440c54ffae",
    ".holoctl/board/tickets/_template.md": "2989a12cb2338b322af7fe42517b680b378ffec73a30d781b6fe4a065c55d0b3",
    ".holoctl/commands/agent-new.md": "5699a1f20dc1a8e927f888693a231de5751813f1986c02e9c0129455cebfa36c",
    ".holoctl/commands/board.md": "4b4136ef4d73dc9f2955be2afbacd63c35fa7be139324f46c6e6c7fdef1dceb8",
    ".holoctl/commands/close.md": "8999bfe41d8037bef1b142427b167bddbb7986157befb756264a207b52857f1c",
    ".holoctl/commands/decision.md": "0bb95d772eedb5fb5932e2333dfc808d70b407275cad8a28ba876f5746db2566",
    ".holoctl/commands/spec.md": "2e6cb98118e0834127b135da4f0f90acca0da1a9ec4d52b5220d5036323456e5",
    ".holoctl/commands/sprint.md": "d447f92e3fa944a5dbf214fef25637b735d232f4ef42717a32f7063958d72174",
    ".holoctl/commands/status.md": "9c81537bd41e431d54382c25bd4747472420648fe7a137be12c837e767ddfe9f",
    ".holoctl/commands/ticket.md": "a7d3fdfd661b6a50d35aa7dde1758971ca19dc806af34c290654479a8a584db8",
    ".holoctl/context/architecture.md": "39fd561774654348bd4866b8fc5d4c5e03357b377b44d8535582b24e22c7f4a2",
    ".holoctl/context/conventions.md": "455312898df461b99f3e4579db68e3be441dadcf8bfb7c6ff2782305d0eaafe2",
    ".holoctl/context/objective.md": "e8572e57d502f84bfd9dea9a6e6208bd9227e069977428a138d2f7bf283c5925",
    ".holoctl/instructions.md": "a0c74b5f6eb546b9380840ac586795dfc159df1929f2341283b6f84d60a410c5",
}

# ---------------------------------------------------------------------------
# Snapshot 2 — customized config, exercising every interpolated field
# (name, prefix, non-empty description, custom statuses, non-default boardCli).
# ---------------------------------------------------------------------------
GOLDEN_CUSTOM = {
    ".holoctl/agents/boardmaster.md": "b0ddce284192e931822aad4a4a45734727979d4d64995470963286bdb105555d",
    ".holoctl/board/WORKFLOW.md": "200a043b0ff35f07dfae39cff968b885e624ae310d1e41ff9dae8199612d2161",
    ".holoctl/board/tickets/_template.md": "abcd20f9abda74c732c024fc16ec0701f9a4df1b050fdb158707d4b8e1aed78d",
    ".holoctl/commands/agent-new.md": "b4fe95a321731a58498f26a9eee5eeb1fe2c0cbca40234dbc712ed6d82ecd849",
    ".holoctl/commands/board.md": "f89de4e7a82503f73bdfebd88f1e1e633b0f08214583e4076b4f3fe795e88608",
    ".holoctl/commands/close.md": "1ae54d9700390ff438e37f41fedf09e2515dcf7132d39acb06aa76045dfc6ed2",
    ".holoctl/commands/decision.md": "0bb95d772eedb5fb5932e2333dfc808d70b407275cad8a28ba876f5746db2566",
    ".holoctl/commands/spec.md": "d40f13e6d4b93fca29e6a26e8ec9260e87fc6e8917bcc67af84ee76098d2f6b0",
    ".holoctl/commands/sprint.md": "d447f92e3fa944a5dbf214fef25637b735d232f4ef42717a32f7063958d72174",
    ".holoctl/commands/status.md": "3d2027a8eb350b21309a35e0ea608125f0dd63b2c3392fda8e8babfcd1e31f62",
    ".holoctl/commands/ticket.md": "ff0dfcfd5d9311c36bec6e5473569e02dd6b5f6204a275c6dad5d8a872d33a95",
    ".holoctl/context/architecture.md": "39fd561774654348bd4866b8fc5d4c5e03357b377b44d8535582b24e22c7f4a2",
    ".holoctl/context/conventions.md": "455312898df461b99f3e4579db68e3be441dadcf8bfb7c6ff2782305d0eaafe2",
    ".holoctl/context/objective.md": "b277845b087f647890bd04de3b88fe79d41ce80f44439ce58e976d6a15e5793b",
    ".holoctl/instructions.md": "7485916b722e316aa6b1b990f2ad0fae1769e1aa6d886d52bb5e9cdd7afa5aab",
}


def _custom_config() -> dict:
    cfg = get_defaults()
    cfg["project"]["name"] = "Acme Rocket"
    cfg["project"]["prefix"] = "ACME"
    cfg["project"]["description"] = "A rocket-launch scheduling system."
    cfg["board"]["statuses"] = ["todo", "wip", "qa", "shipped"]
    cfg["commands"]["boardCli"] = "holoctl board"
    return cfg


def _hashes(templates: dict[str, str]) -> dict[str, str]:
    return {k: hashlib.sha256(v.encode("utf-8")).hexdigest() for k, v in templates.items()}


def test_default_config_output_is_byte_identical_to_old_implementation():
    assert _hashes(get_templates(get_defaults())) == GOLDEN_DEFAULT


def test_custom_config_output_is_byte_identical_to_old_implementation():
    assert _hashes(get_templates(_custom_config())) == GOLDEN_CUSTOM


def test_emission_order_preserved():
    """init logs files in dict order — keep the historical order stable."""
    keys = list(get_templates(get_defaults()))
    assert keys[:3] == [
        ".holoctl/board/WORKFLOW.md",
        ".holoctl/board/tickets/_template.md",
        ".holoctl/agents/boardmaster.md",
    ]
    assert keys[-1] == ".holoctl/instructions.md"


def test_every_template_source_exists_on_disk():
    """Each get_templates entry maps to a real file under holoctl/templates/."""
    root = Path(__file__).resolve().parent.parent / "holoctl" / "templates"
    for source in _TEMPLATE_SOURCES.values():
        assert (root / source).is_file(), f"missing template file: templates/{source}"


def test_no_unresolved_placeholders_leak_into_output():
    for key, body in get_templates(get_defaults()).items():
        for line in body.splitlines():
            assert "{{" not in line or "${{" in line, f"unresolved placeholder in {key}: {line!r}"


@pytest.mark.skipif(shutil.which("uv") is None, reason="uv not on PATH")
def test_wheel_ships_the_disk_templates(tmp_path: Path):
    """A wheel built from this tree must contain every template .md the
    disk-loading get_templates() depends on (package-data regression net)."""
    repo = Path(__file__).resolve().parent.parent
    subprocess.run(
        ["uv", "build", "--wheel", "--out-dir", str(tmp_path)],
        cwd=repo, check=True, capture_output=True, timeout=300,
    )
    wheels = list(tmp_path.glob("*.whl"))
    assert len(wheels) == 1, f"expected exactly one wheel, got {wheels}"
    with zipfile.ZipFile(wheels[0]) as zf:
        names = set(zf.namelist())
    for source in _TEMPLATE_SOURCES.values():
        assert f"holoctl/templates/{source}" in names, f"wheel missing templates/{source}"


@pytest.mark.skipif(shutil.which("uv") is None, reason="uv not on PATH")
def test_wheel_install_resolves_templates_via_importlib_resources(tmp_path: Path):
    """From a wheel (no source tree), get_templates() must still produce the
    golden output — proves the importlib.resources path, not just the
    source-tree fallback."""
    repo = Path(__file__).resolve().parent.parent
    subprocess.run(
        ["uv", "build", "--wheel", "--out-dir", str(tmp_path)],
        cwd=repo, check=True, capture_output=True, timeout=300,
    )
    wheel = next(tmp_path.glob("*.whl"))
    site = tmp_path / "site"
    with zipfile.ZipFile(wheel) as zf:
        zf.extractall(site)
    code = (
        "import hashlib, json, sys\n"
        "from holoctl.lib.config import get_defaults\n"
        "from holoctl.lib.templates import get_templates\n"
        "t = get_templates(get_defaults())\n"
        "print(json.dumps({k: hashlib.sha256(v.encode()).hexdigest() for k, v in t.items()}))\n"
    )
    proc = subprocess.run(
        [sys.executable, "-c", code],
        cwd=tmp_path,  # NOT the repo — forces the installed copy, not the source tree
        env={"PYTHONPATH": str(site), "PATH": "/usr/bin:/bin"},
        check=True, capture_output=True, text=True, timeout=120,
    )
    import json

    assert json.loads(proc.stdout) == GOLDEN_DEFAULT
