"""F4 — the hand-edit guard protects the `agents` markdown output, not just Claude.

Post-manifest model (header retired): the `agents` compiler routes AGENTS.md
through the same ledger as Claude. A user's hand-edited `AGENTS.md` (hash drifted
from the manifest) is preserved on recompile — directly upholding the "never
overwrite hand-edited AI configs" rule holoctl ships in the generated `AGENTS.md`.

These call `compile_agents` directly (no orchestrator), so it builds and
finalizes its own target-scoped ledger.
"""
from __future__ import annotations

import os
from pathlib import Path

import pytest

from holoctl.lib.compiler.agents import compile_agents
from holoctl.lib.config import get_defaults


@pytest.fixture(autouse=True)
def _clear_force_env():
    os.environ.pop("HOLOCTL_COMPILE_FORCE", None)
    yield
    os.environ.pop("HOLOCTL_COMPILE_FORCE", None)


def _seed(root: Path) -> None:
    (root / ".holoctl" / "context").mkdir(parents=True, exist_ok=True)
    (root / ".holoctl" / "instructions.md").write_text(
        "# Project\n\nseed instructions.\n", encoding="utf-8"
    )
    (root / ".holoctl" / "context" / "objective.md").write_text(
        "Do the thing.\n", encoding="utf-8"
    )


def _config() -> dict:
    cfg = get_defaults()
    cfg["project"]["name"] = "Drift"
    cfg["project"]["prefix"] = "DR"
    return cfg


# (compiler, output rel path)
_CASES = [
    (compile_agents, "AGENTS.md"),
]


@pytest.mark.parametrize("compiler,out_rel", _CASES)
def test_first_compile_writes_clean_and_tracked(tmp_path: Path, compiler, out_rel: str):
    _seed(tmp_path)
    compiler(tmp_path, _config())
    out = tmp_path / out_rel
    assert out.exists()
    # Headerless.
    assert "Generated by holoctl" not in out.read_text(encoding="utf-8")
    # Manifest-tracked.
    from holoctl.lib.compiler.manifest import load
    assert out_rel in load(tmp_path)["files"]


@pytest.mark.parametrize("compiler,out_rel", _CASES)
def test_hand_edited_output_is_preserved(tmp_path: Path, compiler, out_rel: str):
    _seed(tmp_path)
    compiler(tmp_path, _config())
    out = tmp_path / out_rel

    # User edits the output (hash now drifts from the manifest).
    out.write_text("# Hand-edited\n\nDo not clobber me.\n", encoding="utf-8")
    # Change the source so a naive compiler would rewrite.
    (tmp_path / ".holoctl" / "instructions.md").write_text(
        "# Project\n\nCHANGED source.\n", encoding="utf-8"
    )

    result = compiler(tmp_path, _config())

    surviving = out.read_text(encoding="utf-8")
    assert "Do not clobber me." in surviving
    skip_paths = [s["path"] for s in result.get("skipped", [])]
    assert any(out_rel.split("/")[-1] in p for p in skip_paths), result


@pytest.mark.parametrize("compiler,out_rel", _CASES)
def test_force_overwrites_hand_edited_output(tmp_path: Path, compiler, out_rel: str):
    _seed(tmp_path)
    compiler(tmp_path, _config())
    out = tmp_path / out_rel
    out.write_text("# Hand-edited\n", encoding="utf-8")

    os.environ["HOLOCTL_COMPILE_FORCE"] = "1"
    compiler(tmp_path, _config())

    after = out.read_text(encoding="utf-8")
    assert "Generated by holoctl" not in after
    assert "# Hand-edited" not in after


@pytest.mark.parametrize("compiler,out_rel", _CASES)
def test_legacy_headered_output_is_adopted(tmp_path: Path, compiler, out_rel: str):
    """A pre-manifest headered AGENTS.md (not tracked) is adopted clean on first compile."""
    _seed(tmp_path)
    out = tmp_path / out_rel
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "<!-- Generated by holoctl. Do not edit directly. -->\n\nlegacy body\n",
        encoding="utf-8",
    )
    compiler(tmp_path, _config())
    after = out.read_text(encoding="utf-8")
    assert "Generated by holoctl" not in after
    assert "legacy body" not in after
    from holoctl.lib.compiler.manifest import load
    assert out_rel in load(tmp_path)["files"]
