from __future__ import annotations
from pathlib import Path

from ..markdown import parse_frontmatter
from .template import resolve_template

_HEADER = "<!-- Generated by projhub. Do not edit directly. Source: .projhub/ -->\n\n"

_MODEL_MAP = {"fast": "haiku", "standard": "sonnet", "reasoning": "opus"}
_TOOL_MAP = {
    "read": "Read",
    "search": "Grep, Glob",
    "edit": "Edit",
    "write": "Write",
    "shell": "Bash",
    "browser": "WebSearch, WebFetch",
}


def compile_claude(project_root: Path, config: dict, dry_run: bool = False) -> dict:
    files = []

    agents_dir = project_root / ".projhub" / "agents"
    claude_agents_dir = project_root / ".claude" / "agents"

    if agents_dir.exists():
        if not dry_run:
            claude_agents_dir.mkdir(parents=True, exist_ok=True)
        for f in sorted(agents_dir.glob("*.md")):
            data_fm, body = parse_frontmatter(f.read_text(encoding="utf-8"))
            frontmatter = "\n".join([
                "---",
                f"name: {data_fm.get('name', f.stem)}",
                f"description: {data_fm.get('description', '')}",
                f"tools: {_map_tools(data_fm.get('tools'))}",
                f"model: {_MODEL_MAP.get(data_fm.get('model', 'standard'), data_fm.get('model', 'sonnet'))}",
                "---",
            ])
            resolved_body = resolve_template(body, config)
            output = _HEADER + frontmatter + "\n" + resolved_body
            out_path = f".claude/agents/{f.name}"
            if not dry_run:
                (project_root / out_path).write_text(output, encoding="utf-8")
            files.append(out_path)

    commands_dir = project_root / ".projhub" / "commands"
    claude_commands_dir = project_root / ".claude" / "commands"

    if commands_dir.exists():
        if not dry_run:
            claude_commands_dir.mkdir(parents=True, exist_ok=True)
        for f in sorted(commands_dir.glob("*.md")):
            content = f.read_text(encoding="utf-8")
            output = _HEADER + resolve_template(content, config)
            out_path = f".claude/commands/{f.name}"
            if not dry_run:
                (project_root / out_path).write_text(output, encoding="utf-8")
            files.append(out_path)

    instructions_path = project_root / ".projhub" / "instructions.md"
    if instructions_path.exists():
        content = instructions_path.read_text(encoding="utf-8")
        output = _HEADER + resolve_template(content, config)
        out_path = "CLAUDE.md"
        if not dry_run:
            (project_root / out_path).write_text(output, encoding="utf-8")
        files.append(out_path)

    return {"files": files}


def _map_tools(tools) -> str:
    if not tools:
        return "Read, Grep, Glob, Edit, Write, Bash"
    arr = tools if isinstance(tools, list) else [t.strip() for t in str(tools).split(",")]
    return ", ".join(_TOOL_MAP.get(t, t) for t in arr)
