from __future__ import annotations
from pathlib import Path

from .template import resolve_template

_HEADER = "<!-- Generated by projhub. Do not edit directly. Source: .projhub/ -->\n\n"


def compile_windsurf(project_root: Path, config: dict, dry_run: bool = False) -> dict:
    files = []

    instructions_path = project_root / ".projhub" / "instructions.md"
    if instructions_path.exists():
        content = instructions_path.read_text(encoding="utf-8")
        out_path = ".windsurfrules"
        if not dry_run:
            (project_root / out_path).write_text(
                _HEADER + resolve_template(content, config), encoding="utf-8"
            )
        files.append(out_path)

    return {"files": files}
