"""Compile-time ownership helpers retained after the header→manifest migration.

holoctl used to prefix every generated file with a ``<!-- Generated by holoctl -->``
header and use its presence to tell *our* files (safe to overwrite) from
hand-edited ones. That mechanism is gone: ownership now lives in the manifest
(``.holoctl/.compiled.json``) via content hashes (see ``manifest.CompileLedger``).

Two things survive:

* ``HEADER_MARKER`` — the old header's leading substring. Kept ONLY so the first
  headerless compile can *adopt* (overwrite clean + start tracking) files that
  predate the manifest. Passed to the ledger as ``legacy_marker``.
* ``force()`` — bridges ``hctl compile --force`` through an env var for callers
  that build their own ledger without an explicit ``force`` argument (e.g. a
  direct ``compile_claude`` call in tests). The orchestrator passes ``force``
  explicitly; this is the fallback.
"""
from __future__ import annotations

import os

HEADER_MARKER = "<!-- Generated by holoctl"


def force() -> bool:
    """`--force` flag bridged through env var (set by `hctl compile --force`)."""
    return os.environ.get("HOLOCTL_COMPILE_FORCE") == "1"
