"""Shared hand-edit guard for generated markdown outputs.

holoctl prefixes every file it generates with ``HEADER``. On recompile we use
that marker to tell *our* files (safe to overwrite) from files a human has
edited (must be preserved). Without this, recompiling would silently clobber a
user's hand-edits to ``AGENTS.md`` / ``copilot-instructions.md`` /
``.codex/AGENTS.override.md`` — the exact thing the generated ``AGENTS.md``
tells assistants never to do.

Only apply this to outputs that carry ``HEADER``. Bootstrap commands copied
verbatim from ``templates/`` are headerless and holoctl-owned, so they are
written unconditionally by their compilers (guarding them would misfire on the
second compile and break idempotency).
"""
from __future__ import annotations

import os
from pathlib import Path

HEADER = "<!-- Generated by holoctl. Do not edit directly. Source: .holoctl/ -->\n\n"
HEADER_MARKER = "<!-- Generated by holoctl"


def force() -> bool:
    """`--force` flag bridged through env var (set by `hctl compile --force`)."""
    return os.environ.get("HOLOCTL_COMPILE_FORCE") == "1"


def looks_hand_edited(path: Path) -> bool:
    """True if `path` exists and doesn't carry holoctl's generated header."""
    if not path.exists():
        return False
    try:
        head = path.read_text(encoding="utf-8")[:400]
    except (OSError, UnicodeDecodeError):
        return False
    return HEADER_MARKER not in head


def safe_write_md(path: Path, content: str, *, skipped: list[dict]) -> bool:
    """Write `content` to `path` unless it looks hand-edited (no holoctl header).

    Returns True if written, False if skipped. Skipped entries are appended to
    `skipped` for CLI reporting. `--force` bypasses the check.
    """
    if not force() and looks_hand_edited(path):
        skipped.append({
            "path": str(path),
            "reason": "hand-edited (no holoctl header); pass --force to overwrite",
        })
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True
