"""Compile target: AGENTS.md (cross-tool universal).

Emits a root-level `AGENTS.md` that 20+ AI assistants respect (Claude Code,
OpenAI Codex, GitHub Copilot, Cursor, Devin, Zed, Aider, JetBrains Junie,
Google Jules, Factory, goose, Windsurf, UiPath Autopilot, VS Code, ...).

Decoupled from any specific assistant: this is the *neutral interop file*.
Tool-specific compilers (claude/cursor/devin/...) emit their own per-tool
files; this one fills the gap that AGENTS.md is the only true cross-tool
standard for instructions.

Sourcing rules (priority):
  1. `.holoctl/context/objective.md`        → Project / Objective sections
  2. `.holoctl/context/architecture.md`     → Architecture overview
  3. `.holoctl/context/conventions.md`      → Conventions
  4. Detected build/test commands           → Build / Test sections
  5. Subprojects (config.project.repos[])   → Sub-projects section
  6. Holoctl quick reference                → How agents should operate

The output is plain Markdown. No frontmatter (AGENTS.md spec doesn't define
one — keeping it minimal maximizes adoption).
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Optional

from .template import resolve_template

_HEADER = "<!-- Generated by holoctl. Do not edit directly. Source: .holoctl/ -->\n\n"


def compile_agents(project_root: Path, config: dict, dry_run: bool = False) -> dict:
    """Emit `AGENTS.md` at the project root.

    Idempotent: re-running produces the same content for unchanged inputs.
    """
    files = []

    project_name = config.get("project", {}).get("name", project_root.name)
    objective = _read_section(project_root / ".holoctl" / "context" / "objective.md")
    architecture = _read_section(project_root / ".holoctl" / "context" / "architecture.md")
    conventions = _read_section(project_root / ".holoctl" / "context" / "conventions.md")
    build_cmds, test_cmds = _detect_commands(project_root)
    subprojects = config.get("project", {}).get("repos", []) or []
    holoctl_version = config.get("holoctlVersion", "?")

    sections = []
    sections.append(f"# AGENTS.md — {project_name}\n")
    sections.append(
        "This file gives coding agents the context to work productively in "
        "this repo. It's the cross-tool standard ([agents.md](https://agents.md/)) "
        "respected by Claude Code, OpenAI Codex, GitHub Copilot, Cursor, Devin, "
        "Zed, Aider and 15+ other assistants.\n"
    )

    if objective:
        sections.append("## Objective\n\n" + objective.strip() + "\n")

    if architecture:
        sections.append("## Architecture\n\n" + architecture.strip() + "\n")

    if conventions:
        sections.append("## Conventions\n\n" + conventions.strip() + "\n")

    if build_cmds:
        sections.append(
            "## Build commands\n\n"
            + "\n".join(f"- `{c}`" for c in build_cmds)
            + "\n"
        )

    if test_cmds:
        sections.append(
            "## Test commands\n\n"
            + "\n".join(f"- `{c}`" for c in test_cmds)
            + "\n"
        )

    if subprojects:
        rows = ["| Path | Name | Description |", "|---|---|---|"]
        for r in subprojects:
            path = r.get("path", "?")
            name = r.get("name", "")
            desc = (r.get("description") or "").replace("|", "\\|")
            rows.append(f"| `{path}` | {name} | {desc} |")
        sections.append("## Sub-projects\n\n" + "\n".join(rows) + "\n")

    sections.append(_holoctl_quick_reference(holoctl_version))

    body = "\n".join(sections)
    body = resolve_template(body, config)
    output = _HEADER + body

    out_path = "AGENTS.md"
    if not dry_run:
        (project_root / out_path).write_text(output, encoding="utf-8")
    files.append(out_path)

    return {"files": files}


def _read_section(path: Path) -> Optional[str]:
    """Return the body of a markdown file (without frontmatter), or None."""
    if not path.exists():
        return None
    raw = path.read_text(encoding="utf-8")
    # Strip YAML frontmatter if present.
    if raw.startswith("---\n"):
        end = raw.find("\n---\n", 4)
        if end != -1:
            raw = raw[end + 5 :]
    return raw.strip() or None


def _detect_commands(project_root: Path) -> tuple[list[str], list[str]]:
    """Best-effort detection of build/test commands from package files.

    Returns (build_cmds, test_cmds). Each list is small (<=4) and contains
    actual invocations the agent can run directly.
    """
    build, test = [], []

    pkg_json = project_root / "package.json"
    if pkg_json.exists():
        try:
            data = json.loads(pkg_json.read_text(encoding="utf-8"))
            scripts = data.get("scripts", {}) or {}
            for key in ("build", "compile", "dev"):
                if key in scripts:
                    build.append(f"npm run {key}")
            for key in ("test", "test:unit", "test:ci"):
                if key in scripts:
                    test.append(f"npm run {key}")
        except (json.JSONDecodeError, OSError):
            pass

    pyproject = project_root / "pyproject.toml"
    if pyproject.exists():
        try:
            content = pyproject.read_text(encoding="utf-8")
            # Heuristic — look for common scripts/build-system markers.
            if "[tool.poetry.scripts]" in content or "[project.scripts]" in content:
                build.append("# see pyproject.toml [project.scripts]")
            if "pytest" in content:
                test.append("pytest")
            if "[tool.hatch" in content:
                build.append("hatch build")
            if "uv" in content.lower() or (project_root / "uv.lock").exists():
                build.append("uv sync")
        except OSError:
            pass

    if (project_root / "Cargo.toml").exists():
        build.append("cargo build")
        test.append("cargo test")

    if (project_root / "go.mod").exists():
        build.append("go build ./...")
        test.append("go test ./...")

    if (project_root / "Makefile").exists():
        # Don't enumerate targets — just point at it.
        build.append("make           # see Makefile for available targets")

    if (project_root / "Justfile").exists() or (project_root / "justfile").exists():
        build.append("just           # see Justfile for available recipes")

    # Dedupe preserving order.
    return _dedup(build), _dedup(test)


def _dedup(items: list[str]) -> list[str]:
    seen = set()
    out = []
    for it in items:
        if it not in seen:
            seen.add(it)
            out.append(it)
    return out


def _holoctl_quick_reference(version: str) -> str:
    return f"""## How to operate (holoctl-managed repo)

This repo is managed by **holoctl** (`{version}`). The source of truth lives
in `.holoctl/` — it materializes per-tool config via `hctl compile`.

Common commands you can run:

| Need | Command |
|---|---|
| Read project state | `hctl boot` |
| Inspect everything | `hctl overview` |
| List tickets | `hctl board ls` |
| Create a ticket | `hctl board add '<json>'` |
| List personas | `hctl agent list` |
| Search memory | `hctl memory search <query>` |
| Curator suggestions | `hctl curate show` |
| End-of-session save | `hctl handoff` |

**Hard rules:**

- Never edit `.holoctl/board/index.json` or `.holoctl/memory/MEMORY.md` by
  hand. Use `hctl <subcommand>`.
- Never overwrite hand-edited AI configs (`CLAUDE.md`, `.cursor/rules/`,
  populated `AGENTS.md` sections outside the holoctl-generated block) — read
  for context.
- Slash command equivalent: `/holoctl` (or `holoctl` skill). It detects
  workspace state and routes to init / upgrade / operate.
"""
