from __future__ import annotations
import os
from datetime import datetime, timezone
from pathlib import Path

from ..markdown import parse_frontmatter
from . import hooks_emit, mcp_emit, memory_emit
from .template import load_bootstrap, resolve_template

_HEADER = "<!-- Generated by holoctl. Do not edit directly. Source: .holoctl/ -->\n\n"
_HEADER_MARKER = "<!-- Generated by holoctl"


def _force() -> bool:
    """`--force` flag bridged through env var (set by `hctl compile --force`)."""
    return os.environ.get("HOLOCTL_COMPILE_FORCE") == "1"


def _looks_hand_edited(path: Path) -> bool:
    """True if file exists and doesn't carry holoctl's generated header."""
    if not path.exists():
        return False
    try:
        head = path.read_text(encoding="utf-8")[:400]
    except (OSError, UnicodeDecodeError):
        return False
    return _HEADER_MARKER not in head


def _safe_write_md(path: Path, content: str, *, skipped: list[dict]) -> bool:
    """Write `content` to `path` unless it looks hand-edited (no holoctl header).

    Returns True if written, False if skipped. Skipped entries are appended to
    `skipped` for CLI reporting. `--force` bypasses the check.
    """
    if not _force() and _looks_hand_edited(path):
        skipped.append({
            "path": str(path),
            "reason": "hand-edited (no holoctl header); pass --force to overwrite",
        })
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True

_MODEL_MAP = {"fast": "haiku", "standard": "sonnet", "reasoning": "opus"}
_TOOL_MAP = {
    "read": "Read",
    "search": "Grep, Glob",
    "edit": "Edit",
    "write": "Write",
    "shell": "Bash",
    "browser": "WebSearch, WebFetch",
}


def compile_claude(project_root: Path, config: dict, dry_run: bool = False) -> dict:
    files = []
    skipped: list[dict] = []

    agents_dir = project_root / ".holoctl" / "agents"
    claude_agents_dir = project_root / ".claude" / "agents"

    if agents_dir.exists():
        if not dry_run:
            claude_agents_dir.mkdir(parents=True, exist_ok=True)
        for f in sorted(agents_dir.glob("*.md")):
            data_fm, body = parse_frontmatter(f.read_text(encoding="utf-8"))
            # Build Claude-native frontmatter. Filters out holoctl-private metadata
            # (`when_to_suggest`, `trigger`, `tools`-as-categories) which the
            # curator reads from the source files but Claude Code does not need.
            fm_lines = [
                "---",
                f"name: {data_fm.get('name', f.stem)}",
                f"description: {data_fm.get('description', '')}",
                f"tools: {_map_tools(data_fm.get('tools'))}",
                f"model: {_MODEL_MAP.get(data_fm.get('model', 'standard'), data_fm.get('model', 'sonnet'))}",
            ]
            # `paths:` is Claude Code-native auto-trigger for subagents.
            paths_val = data_fm.get("paths")
            if paths_val:
                if isinstance(paths_val, list):
                    fm_lines.append("paths:")
                    for p in paths_val:
                        fm_lines.append(f"  - {p}")
                else:
                    # Comma-separated string fallback.
                    fm_lines.append("paths:")
                    for p in str(paths_val).split(","):
                        p = p.strip()
                        if p:
                            fm_lines.append(f"  - {p}")
            fm_lines.append("---")
            frontmatter = "\n".join(fm_lines)
            resolved_body = resolve_template(body, config)
            output = _HEADER + frontmatter + "\n" + resolved_body
            out_path = f".claude/agents/{f.name}"
            if not dry_run:
                if _safe_write_md(project_root / out_path, output, skipped=skipped):
                    files.append(out_path)
            else:
                files.append(out_path)

    commands_dir = project_root / ".holoctl" / "commands"
    claude_commands_dir = project_root / ".claude" / "commands"

    if commands_dir.exists():
        if not dry_run:
            claude_commands_dir.mkdir(parents=True, exist_ok=True)
        for f in sorted(commands_dir.glob("*.md")):
            content = f.read_text(encoding="utf-8")
            output = _HEADER + resolve_template(content, config)
            out_path = f".claude/commands/{f.name}"
            if not dry_run:
                if _safe_write_md(project_root / out_path, output, skipped=skipped):
                    files.append(out_path)
            else:
                files.append(out_path)

    instructions_path = project_root / ".holoctl" / "instructions.md"
    if instructions_path.exists():
        content = instructions_path.read_text(encoding="utf-8")
        rendered = resolve_template(content, config)
        # Append a memory pointer block when .holoctl/memory/ exists. Coexists
        # with Claude's native auto-memory (item 11 of the multi-assistant plan).
        if (project_root / ".holoctl" / "memory").exists():
            rendered = rendered.rstrip() + memory_emit.claude_memory_reference_block()
        output = _HEADER + rendered
        out_path = "CLAUDE.md"
        claude_md_path = project_root / out_path
        # M11: CLAUDE.md gets defensive treatment — if hand-edited (no header),
        # preserve via rename to CLAUDE.local.md instead of skip-or-overwrite.
        if not dry_run:
            wrote = _materialize_claude_md(claude_md_path, output, skipped=skipped)
            if wrote:
                files.append(out_path)
        else:
            files.append(out_path)

    # Path-scoped rules → .claude/rules/<name>.md (with `paths:` frontmatter)
    rules_src = project_root / ".holoctl" / "rules"
    if rules_src.exists():
        rules_out = project_root / ".claude" / "rules"
        if not dry_run:
            rules_out.mkdir(parents=True, exist_ok=True)
        for f in sorted(rules_src.glob("*.md")):
            content = f.read_text(encoding="utf-8")
            output = _HEADER + resolve_template(content, config)
            out_path = f".claude/rules/{f.name}"
            if not dry_run:
                (project_root / out_path).write_text(output, encoding="utf-8")
            files.append(out_path)

    # Built-in skills shipped with the holoctl package — reactive skills that
    # the agent auto-triggers via `description:` matching. These live in
    # `holoctl/templates/skills/` and are emitted on every compile.
    files.extend(_emit_builtin_skills(project_root, config, dry_run=dry_run))

    # Custom skills (with progressive disclosure) → .claude/skills/<name>/
    skills_src = project_root / ".holoctl" / "skills"
    if skills_src.exists():
        for skill_dir in sorted(p for p in skills_src.iterdir() if p.is_dir()):
            name = skill_dir.name
            skill_md = skill_dir / "SKILL.md"
            if not skill_md.exists():
                continue
            out_dir = project_root / ".claude" / "skills" / name
            if not dry_run:
                out_dir.mkdir(parents=True, exist_ok=True)
            content = skill_md.read_text(encoding="utf-8")
            out_path = f".claude/skills/{name}/SKILL.md"
            if not dry_run:
                (project_root / out_path).write_text(
                    _HEADER + resolve_template(content, config), encoding="utf-8"
                )
            files.append(out_path)
            # Copy support files (references/, scripts/, templates/) verbatim.
            import shutil as _shutil
            for support in ("references", "scripts", "templates"):
                support_src = skill_dir / support
                if support_src.exists() and not dry_run:
                    support_dst = out_dir / support
                    if support_dst.exists():
                        _shutil.rmtree(support_dst)
                    _shutil.copytree(support_src, support_dst)
                    for sf in support_src.rglob("*"):
                        if sf.is_file():
                            rel = sf.relative_to(skill_dir)
                            files.append(f".claude/skills/{name}/{rel.as_posix()}")

    # Output styles → .claude/output_styles/<name>.md (Claude Code-specific)
    styles_src = project_root / ".holoctl" / "output_styles"
    if styles_src.exists():
        styles_out = project_root / ".claude" / "output_styles"
        if not dry_run:
            styles_out.mkdir(parents=True, exist_ok=True)
        for f in sorted(styles_src.glob("*.md")):
            content = f.read_text(encoding="utf-8")
            out_path = f".claude/output_styles/{f.name}"
            if not dry_run:
                (project_root / out_path).write_text(
                    _HEADER + resolve_template(content, config), encoding="utf-8"
                )
            files.append(out_path)

    # Memory topics → .claude/skills/holoctl-memory-*/SKILL.md
    files.extend(memory_emit.emit_claude(project_root, dry_run=dry_run))

    # Hooks (journal/curator) + write-tool permissions → .claude/settings.json
    files.extend(hooks_emit.emit_claude(project_root, dry_run=dry_run))

    # MCP server config → .claude/settings.json:mcpServers.holoctl
    files.extend(mcp_emit.emit_claude(project_root, dry_run=dry_run))

    bootstrap = load_bootstrap("holoctl-claude.md")
    if bootstrap:
        out_path = ".claude/commands/holoctl.md"
        if not dry_run:
            claude_commands_dir.mkdir(parents=True, exist_ok=True)
            (project_root / out_path).write_text(bootstrap, encoding="utf-8")
        files.append(out_path)

    upgrade_bootstrap = load_bootstrap("hctl-upgrade-claude.md")
    if upgrade_bootstrap:
        out_path = ".claude/commands/hctl-upgrade.md"
        if not dry_run:
            claude_commands_dir.mkdir(parents=True, exist_ok=True)
            (project_root / out_path).write_text(upgrade_bootstrap, encoding="utf-8")
        files.append(out_path)

    result = {"files": files}
    if skipped:
        result["skipped"] = skipped
    return result


def _map_tools(tools) -> str:
    if not tools:
        return "Read, Grep, Glob, Edit, Write, Bash"
    arr = tools if isinstance(tools, list) else [t.strip() for t in str(tools).split(",")]
    return ", ".join(_TOOL_MAP.get(t, t) for t in arr)


def _materialize_claude_md(claude_md_path: Path, generated_content: str, *, skipped: list[dict]) -> bool:
    """Write CLAUDE.md, preserving any hand-edited content via rename.

    Behavior:
      - File doesn't exist → write new.
      - File exists with holoctl header → safe to overwrite (we generated it).
      - File exists WITHOUT header (hand-edited) AND --force not passed →
        rename to `CLAUDE.local.md` to preserve, then write new.
      - File exists WITHOUT header AND --force passed → backup to
        `.claude/.cache/CLAUDE.backup-<ts>.md`, then overwrite.
    """
    if not claude_md_path.exists():
        claude_md_path.parent.mkdir(parents=True, exist_ok=True)
        claude_md_path.write_text(generated_content, encoding="utf-8")
        return True

    existing = claude_md_path.read_text(encoding="utf-8")
    if _HEADER_MARKER in existing[:400]:
        # Ours — safe to regenerate.
        claude_md_path.write_text(generated_content, encoding="utf-8")
        return True

    # Hand-edited.
    if _force():
        backup_dir = claude_md_path.parent / ".claude" / ".cache"
        backup_dir.mkdir(parents=True, exist_ok=True)
        ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        backup_path = backup_dir / f"CLAUDE.backup-{ts}.md"
        backup_path.write_text(existing, encoding="utf-8")
        claude_md_path.write_text(generated_content, encoding="utf-8")
        skipped.append({
            "path": str(claude_md_path),
            "reason": f"hand-edited; backed up to {backup_path.relative_to(claude_md_path.parent)} before overwrite (--force)",
        })
        return True

    # Default: preserve via rename.
    local_path = claude_md_path.with_name("CLAUDE.local.md")
    if local_path.exists():
        # Don't clobber an existing CLAUDE.local.md either.
        ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        local_path = claude_md_path.with_name(f"CLAUDE.local.{ts}.md")
    claude_md_path.rename(local_path)
    claude_md_path.write_text(generated_content, encoding="utf-8")
    skipped.append({
        "path": str(claude_md_path),
        "reason": (
            f"hand-edited CLAUDE.md preserved as {local_path.name}; "
            f"move its content into .holoctl/instructions.md or pass --force to overwrite"
        ),
    })
    return True


def _emit_builtin_skills(project_root: Path, config: dict, dry_run: bool = False) -> list[str]:
    """Copy built-in reactive skills from the holoctl package into `.claude/skills/`.

    Each subdir of `holoctl/templates/skills/` becomes a skill. Templates are
    resolved against `config` so `{{project.name}}` etc. work. Support files
    (`references/`, `scripts/`, `templates/`) are copied verbatim.
    """
    import shutil as _shutil
    files: list[str] = []
    try:
        from importlib.resources import files as _ires_files
        skills_root = _ires_files("holoctl") / "templates" / "skills"
    except (ModuleNotFoundError, AttributeError):
        skills_root = (
            Path(__file__).resolve().parent.parent.parent / "templates" / "skills"
        )
    # `importlib.resources` returns a Traversable; convert to Path when possible.
    skills_root_path = Path(str(skills_root))
    if not skills_root_path.exists():
        return []

    out_skills_dir = project_root / ".claude" / "skills"

    for skill_dir in sorted(p for p in skills_root_path.iterdir() if p.is_dir()):
        name = skill_dir.name
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            continue
        out_dir = out_skills_dir / name
        if not dry_run:
            out_dir.mkdir(parents=True, exist_ok=True)
        content = skill_md.read_text(encoding="utf-8")
        out_skill_path = f".claude/skills/{name}/SKILL.md"
        if not dry_run:
            (project_root / out_skill_path).write_text(
                _HEADER + resolve_template(content, config), encoding="utf-8"
            )
        files.append(out_skill_path)
        for support in ("references", "scripts", "templates"):
            support_src = skill_dir / support
            if support_src.exists() and not dry_run:
                support_dst = out_dir / support
                if support_dst.exists():
                    _shutil.rmtree(support_dst)
                _shutil.copytree(support_src, support_dst)
                for sf in support_src.rglob("*"):
                    if sf.is_file():
                        rel = sf.relative_to(skill_dir)
                        files.append(f".claude/skills/{name}/{rel.as_posix()}")
    return files
