from __future__ import annotations
from pathlib import Path

from ..markdown import parse_frontmatter
from . import hooks_emit, mcp_emit, memory_emit
from .template import load_bootstrap, resolve_template

_HEADER = "<!-- Generated by holoctl. Do not edit directly. Source: .holoctl/ -->\n\n"

_MODEL_MAP = {"fast": "haiku", "standard": "sonnet", "reasoning": "opus"}
_TOOL_MAP = {
    "read": "Read",
    "search": "Grep, Glob",
    "edit": "Edit",
    "write": "Write",
    "shell": "Bash",
    "browser": "WebSearch, WebFetch",
}


def compile_claude(project_root: Path, config: dict, dry_run: bool = False) -> dict:
    files = []

    agents_dir = project_root / ".holoctl" / "agents"
    claude_agents_dir = project_root / ".claude" / "agents"

    if agents_dir.exists():
        if not dry_run:
            claude_agents_dir.mkdir(parents=True, exist_ok=True)
        for f in sorted(agents_dir.glob("*.md")):
            data_fm, body = parse_frontmatter(f.read_text(encoding="utf-8"))
            frontmatter = "\n".join([
                "---",
                f"name: {data_fm.get('name', f.stem)}",
                f"description: {data_fm.get('description', '')}",
                f"tools: {_map_tools(data_fm.get('tools'))}",
                f"model: {_MODEL_MAP.get(data_fm.get('model', 'standard'), data_fm.get('model', 'sonnet'))}",
                "---",
            ])
            resolved_body = resolve_template(body, config)
            output = _HEADER + frontmatter + "\n" + resolved_body
            out_path = f".claude/agents/{f.name}"
            if not dry_run:
                (project_root / out_path).write_text(output, encoding="utf-8")
            files.append(out_path)

    commands_dir = project_root / ".holoctl" / "commands"
    claude_commands_dir = project_root / ".claude" / "commands"

    if commands_dir.exists():
        if not dry_run:
            claude_commands_dir.mkdir(parents=True, exist_ok=True)
        for f in sorted(commands_dir.glob("*.md")):
            content = f.read_text(encoding="utf-8")
            output = _HEADER + resolve_template(content, config)
            out_path = f".claude/commands/{f.name}"
            if not dry_run:
                (project_root / out_path).write_text(output, encoding="utf-8")
            files.append(out_path)

    instructions_path = project_root / ".holoctl" / "instructions.md"
    if instructions_path.exists():
        content = instructions_path.read_text(encoding="utf-8")
        rendered = resolve_template(content, config)
        # Append a memory pointer block when .holoctl/memory/ exists. Coexists
        # with Claude's native auto-memory (item 11 of the multi-assistant plan).
        if (project_root / ".holoctl" / "memory").exists():
            rendered = rendered.rstrip() + memory_emit.claude_memory_reference_block()
        output = _HEADER + rendered
        out_path = "CLAUDE.md"
        if not dry_run:
            (project_root / out_path).write_text(output, encoding="utf-8")
        files.append(out_path)

    # Path-scoped rules → .claude/rules/<name>.md (with `paths:` frontmatter)
    rules_src = project_root / ".holoctl" / "rules"
    if rules_src.exists():
        rules_out = project_root / ".claude" / "rules"
        if not dry_run:
            rules_out.mkdir(parents=True, exist_ok=True)
        for f in sorted(rules_src.glob("*.md")):
            content = f.read_text(encoding="utf-8")
            output = _HEADER + resolve_template(content, config)
            out_path = f".claude/rules/{f.name}"
            if not dry_run:
                (project_root / out_path).write_text(output, encoding="utf-8")
            files.append(out_path)

    # Custom skills (with progressive disclosure) → .claude/skills/<name>/
    skills_src = project_root / ".holoctl" / "skills"
    if skills_src.exists():
        for skill_dir in sorted(p for p in skills_src.iterdir() if p.is_dir()):
            name = skill_dir.name
            skill_md = skill_dir / "SKILL.md"
            if not skill_md.exists():
                continue
            out_dir = project_root / ".claude" / "skills" / name
            if not dry_run:
                out_dir.mkdir(parents=True, exist_ok=True)
            content = skill_md.read_text(encoding="utf-8")
            out_path = f".claude/skills/{name}/SKILL.md"
            if not dry_run:
                (project_root / out_path).write_text(
                    _HEADER + resolve_template(content, config), encoding="utf-8"
                )
            files.append(out_path)
            # Copy support files (references/, scripts/, templates/) verbatim.
            import shutil as _shutil
            for support in ("references", "scripts", "templates"):
                support_src = skill_dir / support
                if support_src.exists() and not dry_run:
                    support_dst = out_dir / support
                    if support_dst.exists():
                        _shutil.rmtree(support_dst)
                    _shutil.copytree(support_src, support_dst)
                    for sf in support_src.rglob("*"):
                        if sf.is_file():
                            rel = sf.relative_to(skill_dir)
                            files.append(f".claude/skills/{name}/{rel.as_posix()}")

    # Output styles → .claude/output_styles/<name>.md (Claude Code-specific)
    styles_src = project_root / ".holoctl" / "output_styles"
    if styles_src.exists():
        styles_out = project_root / ".claude" / "output_styles"
        if not dry_run:
            styles_out.mkdir(parents=True, exist_ok=True)
        for f in sorted(styles_src.glob("*.md")):
            content = f.read_text(encoding="utf-8")
            out_path = f".claude/output_styles/{f.name}"
            if not dry_run:
                (project_root / out_path).write_text(
                    _HEADER + resolve_template(content, config), encoding="utf-8"
                )
            files.append(out_path)

    # Memory topics → .claude/skills/holoctl-memory-*/SKILL.md
    files.extend(memory_emit.emit_claude(project_root, dry_run=dry_run))

    # Hooks (journal/curator) + write-tool permissions → .claude/settings.json
    files.extend(hooks_emit.emit_claude(project_root, dry_run=dry_run))

    # MCP server config → .claude/settings.json:mcpServers.holoctl
    files.extend(mcp_emit.emit_claude(project_root, dry_run=dry_run))

    bootstrap = load_bootstrap("holoctl-claude.md")
    if bootstrap:
        out_path = ".claude/commands/holoctl.md"
        if not dry_run:
            claude_commands_dir.mkdir(parents=True, exist_ok=True)
            (project_root / out_path).write_text(bootstrap, encoding="utf-8")
        files.append(out_path)

    upgrade_bootstrap = load_bootstrap("hctl-upgrade-claude.md")
    if upgrade_bootstrap:
        out_path = ".claude/commands/hctl-upgrade.md"
        if not dry_run:
            claude_commands_dir.mkdir(parents=True, exist_ok=True)
            (project_root / out_path).write_text(upgrade_bootstrap, encoding="utf-8")
        files.append(out_path)

    return {"files": files}


def _map_tools(tools) -> str:
    if not tools:
        return "Read, Grep, Glob, Edit, Write, Bash"
    arr = tools if isinstance(tools, list) else [t.strip() for t in str(tools).split(",")]
    return ", ".join(_TOOL_MAP.get(t, t) for t in arr)
