"""Compile target: OpenAI Codex CLI.

Codex reads two project-scoped surfaces (per the official docs):

  - ``AGENTS.md`` (and ``AGENTS.override.md``) anywhere from the repo root
    down to the cwd. The cross-tool ``agents`` target already emits the root
    ``AGENTS.md``; this compiler emits a Codex-scoped override at
    ``.codex/AGENTS.override.md`` so the user can keep Codex-specific
    instructions without polluting the universal file.
  - ``.codex/config.toml`` — loaded when the project is trusted. Used for
    ``[mcp_servers.<id>]`` tables. We declare the holoctl stdio MCP server
    here (delegated to ``mcp_emit.emit_codex``).

Codex has no documented per-project surface for slash commands or memory
rules — those live at user-level (``~/.codex/skills/`` etc.) which is
outside ``hctl init``'s scope. Cross-tool ``AGENTS.md`` carries the
project context in a format Codex understands natively.
"""
from __future__ import annotations
from pathlib import Path

from . import mcp_emit
from .template import resolve_template

_HEADER = "<!-- Generated by holoctl. Do not edit directly. Source: .holoctl/ -->\n\n"


def compile_codex(project_root: Path, config: dict, dry_run: bool = False) -> dict:
    files: list[str] = []

    instructions_path = project_root / ".holoctl" / "instructions.md"
    if instructions_path.exists():
        content = instructions_path.read_text(encoding="utf-8")
        out_path = ".codex/AGENTS.override.md"
        if not dry_run:
            (project_root / ".codex").mkdir(parents=True, exist_ok=True)
            (project_root / out_path).write_text(
                _HEADER + resolve_template(content, config), encoding="utf-8"
            )
        files.append(out_path)

    files.extend(mcp_emit.emit_codex(project_root, dry_run=dry_run))

    return {"files": files}
