from __future__ import annotations
from pathlib import Path

from . import mcp_emit, memory_emit
from .template import load_bootstrap, resolve_template

_HEADER = "<!-- Generated by holoctl. Do not edit directly. Source: .holoctl/ -->\n\n"


def compile_copilot(project_root: Path, config: dict, dry_run: bool = False) -> dict:
    files = []
    github_dir = project_root / ".github"
    prompts_dir = github_dir / "prompts"

    instructions_path = project_root / ".holoctl" / "instructions.md"
    if instructions_path.exists():
        content = instructions_path.read_text(encoding="utf-8")
        out_path = ".github/copilot-instructions.md"
        if not dry_run:
            github_dir.mkdir(parents=True, exist_ok=True)
            (project_root / out_path).write_text(
                _HEADER + resolve_template(content, config), encoding="utf-8"
            )
        files.append(out_path)

    commands_dir = project_root / ".holoctl" / "commands"
    if commands_dir.exists():
        if not dry_run:
            prompts_dir.mkdir(parents=True, exist_ok=True)
        for f in sorted(commands_dir.glob("*.md")):
            content = f.read_text(encoding="utf-8")
            output = _HEADER + resolve_template(content, config)
            out_path = f".github/prompts/{f.stem}.prompt.md"
            if not dry_run:
                (project_root / out_path).write_text(output, encoding="utf-8")
            files.append(out_path)

    bootstrap = load_bootstrap("holoctl-copilot.prompt.md")
    if bootstrap:
        out_path = ".github/prompts/holoctl.prompt.md"
        if not dry_run:
            prompts_dir.mkdir(parents=True, exist_ok=True)
            (project_root / out_path).write_text(bootstrap, encoding="utf-8")
        files.append(out_path)

    upgrade_bootstrap = load_bootstrap("hctl-upgrade-copilot.prompt.md")
    if upgrade_bootstrap:
        out_path = ".github/prompts/hctl-upgrade.prompt.md"
        if not dry_run:
            prompts_dir.mkdir(parents=True, exist_ok=True)
            (project_root / out_path).write_text(upgrade_bootstrap, encoding="utf-8")
        files.append(out_path)

    # Memory topics → .github/instructions/holoctl-memory-*.instructions.md
    files.extend(memory_emit.emit_copilot(project_root, dry_run=dry_run))

    # MCP server config → .vscode/mcp.json
    files.extend(mcp_emit.emit_copilot(project_root, dry_run=dry_run))

    return {"files": files}
