from __future__ import annotations
from pathlib import Path

from ..markdown import parse_frontmatter
from .template import resolve_template

_HEADER = "<!-- Generated by holoctl. Do not edit directly. Source: .holoctl/ -->\n\n"


def compile_cursor(project_root: Path, config: dict, dry_run: bool = False) -> dict:
    files = []

    instructions_path = project_root / ".holoctl" / "instructions.md"
    if instructions_path.exists():
        content = instructions_path.read_text(encoding="utf-8")
        out_path = ".cursorrules"
        if not dry_run:
            (project_root / out_path).write_text(
                _HEADER + resolve_template(content, config), encoding="utf-8"
            )
        files.append(out_path)

    agents_dir = project_root / ".holoctl" / "agents"
    cursor_rules_dir = project_root / ".cursor" / "rules"
    if agents_dir.exists():
        if not dry_run:
            cursor_rules_dir.mkdir(parents=True, exist_ok=True)
        for f in sorted(agents_dir.glob("*.md")):
            data_fm, body = parse_frontmatter(f.read_text(encoding="utf-8"))
            resolved = resolve_template(body, config)
            out_path = f".cursor/rules/{f.name}"
            if not dry_run:
                (project_root / out_path).write_text(
                    _HEADER + resolved, encoding="utf-8"
                )
            files.append(out_path)

    return {"files": files}
