from __future__ import annotations
from pathlib import Path

from .template import load_bootstrap, resolve_template

_HEADER = "<!-- Generated by holoctl. Do not edit directly. Source: .holoctl/ -->\n\n"


def compile_cursor(project_root: Path, config: dict, dry_run: bool = False) -> dict:
    files = []

    instructions_path = project_root / ".holoctl" / "instructions.md"
    if instructions_path.exists():
        content = instructions_path.read_text(encoding="utf-8")
        out_path = ".cursor/rules/holoctl.md"
        if not dry_run:
            (project_root / ".cursor" / "rules").mkdir(parents=True, exist_ok=True)
            (project_root / out_path).write_text(
                _HEADER + resolve_template(content, config), encoding="utf-8"
            )
        files.append(out_path)

    commands_dir = project_root / ".holoctl" / "commands"
    cursor_commands_dir = project_root / ".cursor" / "commands"
    if commands_dir.exists():
        if not dry_run:
            cursor_commands_dir.mkdir(parents=True, exist_ok=True)
        for f in sorted(commands_dir.glob("*.md")):
            content = f.read_text(encoding="utf-8")
            output = _HEADER + resolve_template(content, config)
            out_path = f".cursor/commands/{f.name}"
            if not dry_run:
                (project_root / out_path).write_text(output, encoding="utf-8")
            files.append(out_path)

    bootstrap = load_bootstrap("holoctl-cursor.md")
    if bootstrap:
        out_path = ".cursor/commands/holoctl.md"
        if not dry_run:
            cursor_commands_dir.mkdir(parents=True, exist_ok=True)
            (project_root / out_path).write_text(bootstrap, encoding="utf-8")
        files.append(out_path)

    return {"files": files}
