from __future__ import annotations
from pathlib import Path

from ..markdown import parse_frontmatter
from .template import resolve_template

_HEADER = "<!-- Generated by holoctl. Do not edit directly. Source: .holoctl/ -->\n\n"


def compile_devin(project_root: Path, config: dict, dry_run: bool = False) -> dict:
    """Compile to Devin CLI format.

    Devin reads:
    - `AGENTS.md` at the project root (always-active rules, plain Markdown)
    - `.devin/skills/<name>/SKILL.md` per skill (slash command equivalent)
      with YAML frontmatter (name, description).
    """
    files = []

    instructions_path = project_root / ".holoctl" / "instructions.md"
    if instructions_path.exists():
        content = instructions_path.read_text(encoding="utf-8")
        out_path = "AGENTS.md"
        if not dry_run:
            (project_root / out_path).write_text(
                _HEADER + resolve_template(content, config), encoding="utf-8"
            )
        files.append(out_path)

    commands_dir = project_root / ".holoctl" / "commands"
    if commands_dir.exists():
        for f in sorted(commands_dir.glob("*.md")):
            data_fm, body = parse_frontmatter(f.read_text(encoding="utf-8"))
            name = data_fm.get("name", f.stem)
            skill_dir = project_root / ".devin" / "skills" / name
            frontmatter_lines = [
                "---",
                f"name: {name}",
                f"description: {data_fm.get('description', '')}",
            ]
            if data_fm.get("arguments"):
                frontmatter_lines.append(f"arguments: {data_fm['arguments']}")
            frontmatter_lines.append("---")
            output = _HEADER + "\n".join(frontmatter_lines) + "\n\n" + resolve_template(body, config)
            out_path = f".devin/skills/{name}/SKILL.md"
            if not dry_run:
                skill_dir.mkdir(parents=True, exist_ok=True)
                (project_root / out_path).write_text(output, encoding="utf-8")
            files.append(out_path)

    return {"files": files}
