from __future__ import annotations
from pathlib import Path

from ..markdown import parse_frontmatter
from .template import resolve_template

_HEADER = "<!-- Generated by holoctl. Do not edit directly. Source: .holoctl/ -->\n\n"


def compile_generic(project_root: Path, config: dict, dry_run: bool = False) -> dict:
    files = []

    agents_dir = project_root / ".holoctl" / "agents"
    if agents_dir.exists():
        agents_md = _HEADER + "# Agents\n\n"
        for f in sorted(agents_dir.glob("*.md")):
            data_fm, body = parse_frontmatter(f.read_text(encoding="utf-8"))
            resolved = resolve_template(body, config)
            agents_md += f"## {data_fm.get('name', f.stem)}\n\n"
            agents_md += f"- **Model**: {data_fm.get('model', 'standard')}\n"
            agents_md += f"- **Trigger**: {data_fm.get('trigger', 'ticket')}\n"
            if data_fm.get("description"):
                agents_md += f"- **Description**: {data_fm['description']}\n"
            agents_md += "\n" + resolved + "\n---\n\n"
        out_path = "AGENTS.md"
        if not dry_run:
            (project_root / out_path).write_text(agents_md, encoding="utf-8")
        files.append(out_path)

    commands_dir = project_root / ".holoctl" / "commands"
    if commands_dir.exists():
        commands_md = _HEADER + "# Commands\n\n"
        for f in sorted(commands_dir.glob("*.md")):
            content = f.read_text(encoding="utf-8")
            commands_md += resolve_template(content, config) + "\n---\n\n"
        out_path = "COMMANDS.md"
        if not dry_run:
            (project_root / out_path).write_text(commands_md, encoding="utf-8")
        files.append(out_path)

    instructions_path = project_root / ".holoctl" / "instructions.md"
    if instructions_path.exists():
        content = instructions_path.read_text(encoding="utf-8")
        out_path = "AI-INSTRUCTIONS.md"
        if not dry_run:
            (project_root / out_path).write_text(
                _HEADER + resolve_template(content, config), encoding="utf-8"
            )
        files.append(out_path)

    return {"files": files}
