"""Manifest module — tracks holoctl-generated files across compile runs.

Replaces the ``<!-- Generated by holoctl -->`` header approach with a
JSON manifest (``.holoctl/.compiled.json``) that records each generated
file's path and content hash. This allows holoctl to:

- Emit **clean** output files (no header comment).
- Detect **hand-edits** by comparing on-disk hash vs manifest hash.
- **Prune orphans**: files holoctl generated previously but no longer
  does are deleted only if still owned-unmodified; hand-edited orphans
  are left in place.

Only stdlib imports (hashlib, json, datetime, pathlib). No dependency on
other holoctl modules — callers pass ``holoctl_version`` explicitly.
"""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MANIFEST_REL = ".holoctl/.compiled.json"
MANIFEST_VERSION = 1


# ---------------------------------------------------------------------------
# Low-level helpers
# ---------------------------------------------------------------------------


def manifest_path(root: Path) -> Path:
    """Absolute path to the manifest file for *root*."""
    return root / Path(MANIFEST_REL)


def sha256_text(text: str) -> str:
    """Hex SHA-256 digest of *text* encoded as UTF-8."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha256_bytes(data: bytes) -> str:
    """Hex SHA-256 digest of raw *data* bytes."""
    return hashlib.sha256(data).hexdigest()


def _to_posix(rel: str) -> str:
    """Normalise a relative path key to POSIX forward-slash style."""
    return str(PurePosixPath(Path(rel)))


def _default_manifest() -> dict:
    return {"version": MANIFEST_VERSION, "files": {}}


# ---------------------------------------------------------------------------
# Manifest I/O
# ---------------------------------------------------------------------------


def load(root: Path) -> dict:
    """Load the manifest from *root*.

    Returns ``{"version": MANIFEST_VERSION, "files": {}}`` if the file is
    absent, empty, or unparseable — never raises.
    """
    p = manifest_path(root)
    if not p.exists():
        return _default_manifest()
    try:
        raw = p.read_text(encoding="utf-8")
        if not raw.strip():
            return _default_manifest()
        data = json.loads(raw)
        if not isinstance(data, dict) or "files" not in data:
            return _default_manifest()
        return data
    except Exception:
        return _default_manifest()


def save(root: Path, files: dict, *, holoctl_version: str) -> None:
    """Persist a manifest to *root*.

    *files* is a mapping of POSIX relative paths to entry dicts.  Keys are
    sorted and stored with forward-slash separators even on Windows.

    The written JSON has a trailing newline, ``indent=2``, and includes:
    ``version``, ``generated`` (UTC ISO-8601 ending in ``Z``),
    ``holoctlVersion``, and ``files`` (sorted by key).
    """
    # Normalise all keys to POSIX before sorting / writing.
    normalised: dict = {_to_posix(k): v for k, v in files.items()}
    manifest = {
        "version": MANIFEST_VERSION,
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "holoctlVersion": holoctl_version,
        "files": dict(sorted(normalised.items())),
    }
    p = manifest_path(root)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# CompileLedger
# ---------------------------------------------------------------------------


class CompileLedger:
    """Tracks one compile run: files written, preserved (foreign/hand-edited), and pruned.

    Usage::

        ledger = CompileLedger(root)
        ledger.write(".claude/agents/dev.md", content, source="...", target="...")
        ledger.prune_orphans()
        summary = ledger.finalize(holoctl_version="0.20.0")
    """

    def __init__(
        self,
        root: Path,
        *,
        force: bool = False,
        dry_run: bool = False,
    ) -> None:
        self.root = root
        self.force = force
        self.dry_run = dry_run

        prev_manifest = load(root)
        # prev: rel (POSIX) -> {"sha256", "source", "target"}
        self.prev: dict[str, dict] = prev_manifest.get("files", {})

        # Accumulate this run's state.
        self.written: dict[str, dict] = {}   # rel -> entry  (files written/owned)
        self.skipped: list[dict] = []        # {"path", "reason"}
        self.removed: list[str] = []         # rel paths deleted

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _abs(self, rel: str) -> Path:
        """Resolve a POSIX-normalised rel path against self.root."""
        return self.root / Path(rel)

    def _owned_unmodified_text(self, rel: str) -> bool:
        """True if *rel* is in prev and its on-disk content matches prev hash."""
        if rel not in self.prev:
            return False
        p = self._abs(rel)
        if not p.exists():
            return False
        try:
            on_disk = sha256_text(p.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError):
            return False
        return on_disk == self.prev[rel]["sha256"]

    def _owned_unmodified_bytes(self, rel: str) -> bool:
        """True if *rel* is in prev and on-disk bytes hash matches prev hash."""
        if rel not in self.prev:
            return False
        p = self._abs(rel)
        if not p.exists():
            return False
        try:
            on_disk = sha256_bytes(p.read_bytes())
        except OSError:
            return False
        return on_disk == self.prev[rel]["sha256"]

    def _record(self, rel: str, sha: str, *, source: str, target: str) -> None:
        self.written[rel] = {"sha256": sha, "source": source, "target": target}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def write(self, rel: str, content: str, *, source: str, target: str) -> bool:
        """Write *content* to the file at *rel* (POSIX relative path).

        Ownership semantics:

        - File absent → write, record, return ``True``.
        - File present and **owned-unmodified** → overwrite, record, return ``True``.
        - File present and **foreign or hand-edited**:

          - ``force=True`` → overwrite, record, append skipped note, return ``True``.
          - ``force=False`` → do NOT write, append skipped, return ``False``.

        If ``dry_run=True`` the ledger is updated but nothing is written to disk.
        """
        rel = _to_posix(rel)
        abs_path = self._abs(rel)
        sha = sha256_text(content)

        absent = not abs_path.exists()
        owned = self._owned_unmodified_text(rel)

        if absent or owned:
            # Safe to write.
            if not self.dry_run:
                abs_path.parent.mkdir(parents=True, exist_ok=True)
                abs_path.write_text(content, encoding="utf-8")
            self._record(rel, sha, source=source, target=target)
            return True

        # Present but not owned.
        if self.force:
            if not self.dry_run:
                abs_path.parent.mkdir(parents=True, exist_ok=True)
                abs_path.write_text(content, encoding="utf-8")
            self._record(rel, sha, source=source, target=target)
            self.skipped.append({"path": rel, "reason": "overwritten (--force)"})
            return True

        self.skipped.append({
            "path": rel,
            "reason": "external or hand-edited; left as-is (pass --force to overwrite)",
        })
        return False

    def write_bytes(self, rel: str, src: Path, *, source: str, target: str) -> bool:
        """Copy the binary file at *src* to *rel* (POSIX relative path).

        Same ownership semantics as :meth:`write` but uses byte-level hashing.
        """
        rel = _to_posix(rel)
        abs_path = self._abs(rel)
        data = src.read_bytes()
        sha = sha256_bytes(data)

        absent = not abs_path.exists()
        owned = self._owned_unmodified_bytes(rel)

        if absent or owned:
            if not self.dry_run:
                abs_path.parent.mkdir(parents=True, exist_ok=True)
                abs_path.write_bytes(data)
            self._record(rel, sha, source=source, target=target)
            return True

        if self.force:
            if not self.dry_run:
                abs_path.parent.mkdir(parents=True, exist_ok=True)
                abs_path.write_bytes(data)
            self._record(rel, sha, source=source, target=target)
            self.skipped.append({"path": rel, "reason": "overwritten (--force)"})
            return True

        self.skipped.append({
            "path": rel,
            "reason": "external or hand-edited; left as-is (pass --force to overwrite)",
        })
        return False

    def prune_orphans(self) -> None:
        """Delete files holoctl previously owned but did not write this run.

        For each rel in ``self.prev`` not in ``self.written``:

        - On-disk file **absent** → already gone, silently skip (record in removed).
        - On-disk file **owned-unmodified** → delete (record in removed).
        - On-disk file **diverged** (hand-edited) → leave, append to skipped.

        ``dry_run=True``: intentions are recorded but disk is not touched.
        """
        for rel in self.prev:
            if rel in self.written:
                continue  # Already handled this run.

            abs_path = self._abs(rel)

            if not abs_path.exists():
                # Already gone — silently note it.
                self.removed.append(rel)
                continue

            # Try text ownership first; fall back to bytes for binary files.
            try:
                on_disk_sha = sha256_text(abs_path.read_text(encoding="utf-8"))
                owned = on_disk_sha == self.prev[rel]["sha256"]
            except (OSError, UnicodeDecodeError):
                try:
                    on_disk_sha_b = sha256_bytes(abs_path.read_bytes())
                    owned = on_disk_sha_b == self.prev[rel]["sha256"]
                except OSError:
                    owned = False

            if owned:
                if not self.dry_run:
                    abs_path.unlink(missing_ok=True)
                self.removed.append(rel)
            else:
                self.skipped.append({
                    "path": rel,
                    "reason": "orphaned but diverged; left as-is",
                })

    def finalize(self, *, holoctl_version: str) -> dict:
        """Persist the manifest of ``self.written`` and return a summary dict.

        Churn-avoidance: if ``self.written == self.prev`` and the manifest
        file already exists the rewrite is skipped (mtime preserved).

        Returns ``{"written": <int>, "preserved": <int>, "removed": <int>}``.
        """
        if not self.dry_run:
            mp = manifest_path(self.root)
            # Churn-avoidance: skip rewrite if written set is identical to prev.
            skip_write = (
                mp.exists()
                and self.written == self.prev
            )
            if not skip_write:
                save(self.root, self.written, holoctl_version=holoctl_version)

        return {
            "written": len(self.written),
            "preserved": len(self.skipped),
            "removed": len(self.removed),
        }
