"""Compile manifest — tracks holoctl-generated files across compile runs.

``.holoctl/.compiled.json`` records each output's POSIX rel-path, content
hash, source, and target — replacing the old ``<!-- Generated by holoctl -->``
header so outputs are emitted clean. Invariants:

- **Ledger lifecycle** (one ``CompileLedger`` per target per run): ``load``
  the previous manifest → per output, the ownership decision tree in
  ``_commit``: absent or owned-unmodified → write + record; legacy-headered
  → adopt (overwrite clean, start tracking); hand-edited (in prev, hash
  drifted) → preserve, but carry the OLD entry forward so doctor keeps
  classifying it as hand-edited; foreign (never tracked) → preserve, never
  recorded → ``prune_orphans()`` deletes previously-owned paths not written
  this run, only while still owned-unmodified → ``finalize()`` merges this
  run's entries with the OTHER targets' prev entries and persists (the
  rewrite is skipped when nothing changed, preserving mtime).
- **Hash channels**: ``write`` hashes the logical TEXT (UTF-8 string, safe
  across Windows newline translation since verification re-reads via
  ``read_text``); ``write_bytes`` hashes literal on-disk BYTES. A given path
  must use exactly one channel for life — switching channels makes the
  ownership check miss and the file reads as hand-edited. Only
  ``prune_orphans`` tries both, because it can't know which channel wrote
  the file.

Stdlib-only; no holoctl imports — callers pass ``holoctl_version`` explicitly.
"""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MANIFEST_REL = ".holoctl/.compiled.json"
MANIFEST_VERSION = 1


# ---------------------------------------------------------------------------
# Low-level helpers
# ---------------------------------------------------------------------------


def manifest_path(root: Path) -> Path:
    """Absolute path to the manifest file for *root*."""
    return root / Path(MANIFEST_REL)


def sha256_text(text: str) -> str:
    """Hex SHA-256 digest of *text* encoded as UTF-8."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha256_bytes(data: bytes) -> str:
    """Hex SHA-256 digest of raw *data* bytes."""
    return hashlib.sha256(data).hexdigest()


def _to_posix(rel: str) -> str:
    """Normalise a relative path key to POSIX forward-slash style.

    Must work identically on Windows and POSIX hosts.  ``Path(rel)`` is
    OS-dependent — on Windows it parses ``\\`` as a separator, on Linux/macOS
    it does NOT (the backslash is kept as a literal filename character).  So
    we explicitly translate backslashes to forward slashes BEFORE handing the
    string to ``PurePosixPath``; otherwise a Windows-style key passed in on
    Linux (e.g. tests that simulate a Windows write) survives unchanged and
    breaks cross-platform symmetry.
    """
    return str(PurePosixPath(rel.replace("\\", "/")))


def _default_manifest() -> dict:
    return {"version": MANIFEST_VERSION, "files": {}}


# ---------------------------------------------------------------------------
# Manifest I/O
# ---------------------------------------------------------------------------


def load(root: Path) -> dict:
    """Load the manifest from *root*.

    Returns ``{"version": MANIFEST_VERSION, "files": {}}`` if the file is
    absent, empty, or unparseable — never raises.
    """
    p = manifest_path(root)
    if not p.exists():
        return _default_manifest()
    try:
        raw = p.read_text(encoding="utf-8")
        if not raw.strip():
            return _default_manifest()
        data = json.loads(raw)
        if not isinstance(data, dict) or "files" not in data:
            return _default_manifest()
        return data
    except Exception:
        return _default_manifest()


def add_entries(root: Path, new_entries: dict[str, dict], *, holoctl_version: str) -> None:
    """Merge *new_entries* into the manifest and save.

    *new_entries* maps a relative path → ``{"sha256", "source", "target"}``.
    Loads the current manifest, updates ``files`` with *new_entries* (keys
    POSIX-normalised so they match the compiler's keys), and persists via
    :func:`save`.

    This is the adoption hook: ``hctl adopt`` records the CURRENT ``.claude/``
    file's hash here as managed so that the next ``hctl compile`` recognises it
    as owned and regenerates it from ``.holoctl/`` (instead of preserving it as
    foreign).
    """
    current = load(root).get("files", {})
    merged: dict = dict(current)
    for rel, entry in new_entries.items():
        merged[_to_posix(rel)] = entry
    save(root, merged, holoctl_version=holoctl_version)


def save(root: Path, files: dict, *, holoctl_version: str) -> None:
    """Persist a manifest to *root*.

    *files* is a mapping of POSIX relative paths to entry dicts.  Keys are
    sorted and stored with forward-slash separators even on Windows.

    The written JSON has a trailing newline, ``indent=2``, and includes:
    ``version``, ``generated`` (UTC ISO-8601 ending in ``Z``),
    ``holoctlVersion``, and ``files`` (sorted by key).
    """
    # Normalise all keys to POSIX before sorting / writing.
    normalised: dict = {_to_posix(k): v for k, v in files.items()}
    manifest = {
        "version": MANIFEST_VERSION,
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "holoctlVersion": holoctl_version,
        "files": dict(sorted(normalised.items())),
    }
    p = manifest_path(root)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# CompileLedger
# ---------------------------------------------------------------------------


class CompileLedger:
    """Tracks one compile run: files written, preserved (foreign/hand-edited), and pruned.

    Usage::

        ledger = CompileLedger(root)
        ledger.write(".claude/agents/dev.md", content, source="...", target="...")
        ledger.prune_orphans()
        summary = ledger.finalize(holoctl_version="0.20.0")

    Hash-channel contract
    ---------------------
    There are two write channels, and they must never be mixed for the same path:

    * ``write`` (text channel) — hashes the **logical** string content via
      ``sha256_text``, which encodes to UTF-8 before hashing.  On Windows,
      ``Path.write_text`` translates ``\\n``→``\\r\\n`` on disk, so on-disk
      bytes differ from what was hashed; this is intentional and safe because
      ``_hash_text`` reads back through ``read_text`` (same
      translation) before hashing.
    * ``write_bytes`` (byte channel) — hashes **literal** on-disk bytes via
      ``sha256_bytes``; no newline translation occurs.

    A given path **must** use exactly one channel across all compile runs.
    Switching channels between runs will cause the ownership check to fail
    (hash mismatch) and the file will be treated as hand-edited.
    """

    def __init__(
        self,
        root: Path,
        *,
        force: bool = False,
        dry_run: bool = False,
        target: str | None = None,
        legacy_marker: str | None = None,
    ) -> None:
        self.root = root
        self.force = force
        self.dry_run = dry_run
        # ``target`` scopes pruning + finalize so a multi-target compile (one
        # ledger per target) doesn't prune the OTHER target's files. ``None``
        # means "consider every prev entry" (single-target / legacy callers).
        self.target = target
        # ``legacy_marker`` is the old ``<!-- Generated by holoctl -->`` header.
        # Present only so the first headerless compile can *adopt* (overwrite
        # clean + start tracking) files that predate the manifest.
        self.legacy_marker = legacy_marker

        prev_manifest = load(root)
        # prev: rel (POSIX) -> {"sha256", "source", "target"}
        self.prev: dict[str, dict] = prev_manifest.get("files", {})

        # Accumulate this run's state.
        self.written: dict[str, dict] = {}   # rel -> entry  (files written/owned)
        self.skipped: list[dict] = []        # {"path", "reason"}
        self.removed: list[str] = []         # rel paths deleted
        self.migrated: list[str] = []        # rel paths adopted from legacy header

    @classmethod
    def for_target(
        cls,
        root: Path,
        target: str,
        *,
        dry_run: bool = False,
        force: bool = False,
    ) -> "CompileLedger":
        """Construct a ledger for a compile run, wired with the legacy header marker
        so pre-manifest (headered) outputs are adopted on first compile."""
        from ._safe_write import HEADER_MARKER
        return cls(root, force=force, dry_run=dry_run, target=target, legacy_marker=HEADER_MARKER)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _abs(self, rel: str) -> Path:
        """Resolve a POSIX-normalised rel path against self.root."""
        return self.root / Path(rel)

    def _owned_unmodified(
        self,
        rel: str,
        hash_fn: object,
    ) -> bool:
        """True if *rel* is in prev and its on-disk hash (computed by *hash_fn*) matches.

        *hash_fn* must be a callable ``(Path) -> str`` that reads the file and
        returns its hex SHA-256 digest.  Use ``_hash_text`` for the text channel
        and ``_hash_bytes`` for the byte channel.
        """
        if rel not in self.prev:
            return False
        p = self._abs(rel)
        if not p.exists():
            return False
        try:
            on_disk = hash_fn(p)  # type: ignore[operator]
        except (OSError, UnicodeDecodeError):
            return False
        return on_disk == self.prev[rel]["sha256"]

    @staticmethod
    def _hash_text(p: Path) -> str:
        """Hash the logical (decoded) text content of *p*."""
        return sha256_text(p.read_text(encoding="utf-8"))

    @staticmethod
    def _hash_bytes(p: Path) -> str:
        """Hash the raw byte content of *p*."""
        return sha256_bytes(p.read_bytes())

    def _record(self, rel: str, sha: str, *, source: str, target: str) -> None:
        self.written[rel] = {"sha256": sha, "source": source, "target": target}

    # ------------------------------------------------------------------
    # Ownership predicates (public)
    # ------------------------------------------------------------------

    def is_owned_text(self, rel: str) -> bool:
        """True if *rel* is a holoctl-owned, unmodified TEXT output.

        Public wrapper over the text-channel ownership check, used by callers
        (e.g. CLAUDE.md) that manage their own write/preserve logic and need to
        ask "is this file safe for me to regenerate?".
        """
        return self._owned_unmodified(_to_posix(rel), self._hash_text)

    def is_legacy(self, rel: str) -> bool:
        """True if *rel* is a pre-manifest file still carrying the old header.

        Adoption path: a file holoctl generated *before* the manifest existed
        won't be in ``self.prev`` but still starts with the legacy
        ``<!-- Generated by holoctl -->`` marker at byte 0 — legacy holoctl
        ALWAYS prepended the header at the very start of the file, even for
        skill files with YAML frontmatter. Treating it as owned lets the first
        headerless compile overwrite it cleanly and start tracking it, instead
        of mistaking it for a hand-edit.

        The 400-character read window is DEFENSIVE headroom against edge cases
        (e.g. a BOM or stray whitespace) — it does NOT reflect a layout that
        legacy holoctl ever actually emitted.

        Robust to read errors (returns False).
        """
        if not self.legacy_marker:
            return False
        rel = _to_posix(rel)
        if rel in self.prev:
            return False
        p = self._abs(rel)
        if not p.exists():
            return False
        try:
            head = p.read_text(encoding="utf-8")[:400]
        except (OSError, UnicodeDecodeError):
            return False
        return self.legacy_marker in head

    def record_text(self, rel: str, content: str, *, source: str, target: str) -> None:
        """Record *content* in the ledger WITHOUT writing to disk or checking ownership.

        For callers that perform their own disk write + preserve dance (e.g.
        CLAUDE.md's rename-to-``.local`` behavior) but still want the file
        tracked in the manifest so future compiles recognize it as owned and
        ``prune_orphans`` can reason about it.
        """
        self._record(_to_posix(rel), sha256_text(content), source=source, target=target)

    def _commit(
        self,
        rel: str,
        abs_path: Path,
        sha: str,
        write_fn: object,
        *,
        source: str,
        target: str,
        owned: bool,
        legacy: bool = False,
    ) -> bool:
        """Apply the ownership decision tree shared by ``write`` and ``write_bytes``.

        *write_fn* is a callable ``(abs_path: Path) -> None`` that performs the
        actual disk write (text vs bytes).  Returns ``True`` when the file was
        written/recorded, ``False`` when skipped.

        ``legacy`` flags a file adopted via the old header (see ``is_legacy``):
        it is written like an owned file but recorded in ``self.migrated``
        (no skipped note — migration is expected, not a warning).
        """
        absent = not abs_path.exists()

        if legacy and not absent:
            # Adopt: overwrite clean and start tracking. No skipped note.
            if not self.dry_run:
                abs_path.parent.mkdir(parents=True, exist_ok=True)
                write_fn(abs_path)  # type: ignore[operator]
            self._record(rel, sha, source=source, target=target)
            self.migrated.append(rel)
            return True

        if absent or owned:
            # Safe to write (new file or still owned-unmodified).
            #
            # Incremental skip: when the file is OWNED (on-disk hash == recorded
            # hash) AND the freshly generated content hashes to that SAME value,
            # the bytes on disk already match what we'd write. Skip the disk
            # write to avoid churning mtimes / git diffs — but still ``_record``
            # so the manifest entry is carried forward unchanged.
            if (
                owned
                and not absent
                and self.prev.get(rel, {}).get("sha256") == sha
            ):
                self._record(rel, sha, source=source, target=target)
                return True
            if not self.dry_run:
                abs_path.parent.mkdir(parents=True, exist_ok=True)
                write_fn(abs_path)  # type: ignore[operator]
            self._record(rel, sha, source=source, target=target)
            return True

        # Present but not owned.
        if self.force:
            if not self.dry_run:
                abs_path.parent.mkdir(parents=True, exist_ok=True)
                write_fn(abs_path)  # type: ignore[operator]
            self._record(rel, sha, source=source, target=target)
            self.skipped.append({"path": rel, "reason": "overwritten (--force)"})
            return True

        # Present but not owned and not forced → leave on disk.
        #
        # If this path WAS previously holoctl-managed (rel in self.prev), it's a
        # HAND-EDIT of a file we used to own. Carry the previous manifest entry
        # forward (its OLD hash) so finalize keeps recording it. That keeps
        # ``_doctor_compile_drift`` classifying it as hand-edited (rel in manifest,
        # on-disk hash != recorded hash) rather than stale, and stops
        # ``prune_orphans`` from emitting a SECOND skip note (rel now in written).
        #
        # A genuinely FOREIGN file (rel not in self.prev) is NOT recorded —
        # holoctl doesn't own it — so it stays out of the manifest and preserved.
        if rel in self.prev:
            self.written[rel] = self.prev[rel]
            reason = "hand-edited (was holoctl-managed); left as-is (pass --force to overwrite)"
        else:
            reason = "external (not holoctl-managed); left as-is (pass --force to overwrite)"
        self.skipped.append({"path": rel, "reason": reason})
        return False

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def write(self, rel: str, content: str, *, source: str, target: str) -> bool:
        """Write *content* to the file at *rel* (POSIX relative path).

        Uses the **text channel**: content is hashed as a logical UTF-8 string
        via ``sha256_text``.  See the class-level hash-channel contract for why
        this path must never be mixed with ``write_bytes`` for the same file.

        Ownership semantics:

        - File absent → write, record, return ``True``.
        - File present and **owned-unmodified** → overwrite, record, return ``True``.
        - File present and **foreign or hand-edited**:

          - ``force=True`` → overwrite, record, append skipped note, return ``True``.
          - ``force=False`` → do NOT write, append skipped, return ``False``.

        If ``dry_run=True`` the ledger is updated but nothing is written to disk.
        """
        rel = _to_posix(rel)
        abs_path = self._abs(rel)
        sha = sha256_text(content)
        owned = self._owned_unmodified(rel, self._hash_text)
        legacy = (not owned) and self.is_legacy(rel)
        return self._commit(
            rel, abs_path, sha,
            lambda p: p.write_text(content, encoding="utf-8"),
            source=source, target=target, owned=owned, legacy=legacy,
        )

    def write_bytes(self, rel: str, src: Path, *, source: str, target: str) -> bool:
        """Copy the binary file at *src* to *rel* (POSIX relative path).

        Uses the **byte channel**: content is hashed as raw bytes via
        ``sha256_bytes``.  See the class-level hash-channel contract for why
        this path must never be mixed with ``write`` for the same file.

        Same ownership semantics as :meth:`write`.
        """
        rel = _to_posix(rel)
        abs_path = self._abs(rel)
        data = src.read_bytes()
        sha = sha256_bytes(data)
        owned = self._owned_unmodified(rel, self._hash_bytes)
        legacy = (not owned) and self.is_legacy(rel)
        return self._commit(
            rel, abs_path, sha,
            lambda p: p.write_bytes(data),
            source=source, target=target, owned=owned, legacy=legacy,
        )

    def prune_orphans(self) -> None:
        """Delete files holoctl previously owned but did not write this run.

        For each rel in ``self.prev`` not in ``self.written``:

        - On-disk file **absent** → already gone, silently skip (record in removed).
        - On-disk file **owned-unmodified** → delete (record in removed).
        - On-disk file **diverged** (hand-edited) → leave, append to skipped.

        Target-scoped: when ``self.target`` is set, prev entries belonging to a
        DIFFERENT target are left entirely alone (not pruned, not reported). This
        is essential because ``compile_project`` runs one ledger per target — a
        ``claude`` run must not prune the ``agents`` target's files just because
        it didn't write them.

        ``dry_run=True``: intentions are recorded but disk is not touched.
        """
        for rel, entry in self.prev.items():
            if rel in self.written:
                continue  # Already handled this run.

            # Skip prev entries owned by another target (multi-target compile).
            if self.target is not None and entry.get("target") != self.target:
                continue

            abs_path = self._abs(rel)

            if not abs_path.exists():
                # Already gone — silently note it.
                self.removed.append(rel)
                continue

            # Determine ownership, trying both hash channels.
            #
            # Files written via write() (text channel) and write_bytes() (byte
            # channel) share the same manifest schema but differ in how the SHA
            # was computed.  prune_orphans() doesn't know which channel was used,
            # so it tries text first; if that doesn't match, it tries bytes before
            # concluding "diverged".  This correctly handles:
            #   - Text files written via write() on Windows (LF→CRLF on disk).
            #   - Binary / verbatim files written via write_bytes().
            #   - Genuine hand-edits, which won't match either channel's hash.
            owned = (
                self._owned_unmodified(rel, self._hash_text)
                or self._owned_unmodified(rel, self._hash_bytes)
            )

            if owned:
                if not self.dry_run:
                    abs_path.unlink(missing_ok=True)
                    # Parent dirs (references/, scripts/, templates/) are left
                    # in place when emptied — they are inert and ignored by Claude Code.
                self.removed.append(rel)
            else:
                self.skipped.append({
                    "path": rel,
                    "reason": "orphaned but diverged; left as-is",
                })

    def finalize(self, *, holoctl_version: str) -> dict:
        """Persist the merged manifest and return a summary dict.

        Merge semantics (essential for multi-target compiles): the saved manifest
        is this run's ``self.written`` merged with the prev entries that belong to
        OTHER targets. A ``claude`` ledger must not drop the ``agents`` target's
        manifest entries just because it didn't write them. When ``self.target``
        is ``None`` (single-target / legacy), no foreign entries are kept and the
        manifest is simply ``self.written`` (back-compat).

        Churn-avoidance: if the merged map equals ``self.prev`` and the manifest
        file already exists the rewrite is skipped (mtime preserved).

        Returns ``{"written", "preserved", "removed", "migrated"}`` counts.
        """
        # Keep prev entries owned by other targets (or, when target is None,
        # keep none — this run is authoritative for everything it touched).
        merged: dict[str, dict] = {}
        if self.target is not None:
            for rel, entry in self.prev.items():
                if entry.get("target") != self.target:
                    merged[rel] = entry
        merged.update(self.written)

        if not self.dry_run:
            mp = manifest_path(self.root)
            # Churn-avoidance: skip rewrite if the merged map is identical to prev.
            skip_write = mp.exists() and merged == self.prev
            if not skip_write:
                save(self.root, merged, holoctl_version=holoctl_version)

        return {
            "written": len(self.written),
            "preserved": len(self.skipped),
            "removed": len(self.removed),
            "migrated": len(self.migrated),
        }
