from __future__ import annotations
from pathlib import Path

from . import memory_emit
from .template import load_bootstrap, resolve_template

_HEADER = "<!-- Generated by holoctl. Do not edit directly. Source: .holoctl/ -->\n\n"


def compile_windsurf(project_root: Path, config: dict, dry_run: bool = False) -> dict:
    files = []

    instructions_path = project_root / ".holoctl" / "instructions.md"
    if instructions_path.exists():
        content = instructions_path.read_text(encoding="utf-8")
        out_path = ".windsurfrules"
        if not dry_run:
            (project_root / out_path).write_text(
                _HEADER + resolve_template(content, config), encoding="utf-8"
            )
        files.append(out_path)

    commands_dir = project_root / ".holoctl" / "commands"
    workflows_dir = project_root / ".windsurf" / "workflows"
    if commands_dir.exists():
        if not dry_run:
            workflows_dir.mkdir(parents=True, exist_ok=True)
        for f in sorted(commands_dir.glob("*.md")):
            content = f.read_text(encoding="utf-8")
            output = _HEADER + resolve_template(content, config)
            out_path = f".windsurf/workflows/{f.name}"
            if not dry_run:
                (project_root / out_path).write_text(output, encoding="utf-8")
            files.append(out_path)

    bootstrap = load_bootstrap("holoctl-windsurf.md")
    if bootstrap:
        out_path = ".windsurf/workflows/holoctl.md"
        if not dry_run:
            workflows_dir.mkdir(parents=True, exist_ok=True)
            (project_root / out_path).write_text(bootstrap, encoding="utf-8")
        files.append(out_path)

    upgrade_bootstrap = load_bootstrap("hctl-upgrade-windsurf.md")
    if upgrade_bootstrap:
        out_path = ".windsurf/workflows/hctl-upgrade.md"
        if not dry_run:
            workflows_dir.mkdir(parents=True, exist_ok=True)
            (project_root / out_path).write_text(upgrade_bootstrap, encoding="utf-8")
        files.append(out_path)

    # Memory topics → .windsurf/rules/holoctl-memory-*.md (durable, versioned)
    files.extend(memory_emit.emit_windsurf(project_root, dry_run=dry_run))

    return {"files": files}
