from __future__ import annotations
import os
from typing import Optional

import typer
from ._console import console

from ..lib.config import find_project_root, load_config
from ..lib.compiler import compile_project

app = typer.Typer()


@app.command("compile")
def compile_cmd(
    target: Optional[str] = typer.Option(None, "--target", help="Target (agents, claude, copilot, codex)"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview without writing files"),
    force: bool = typer.Option(
        False, "--force", "-f",
        help="Overwrite outputs even if they look hand-edited (header missing or content drifted)."
    ),
):
    """Compile .holoctl/ to tool-specific files.

    By default, refuses to overwrite outputs that look hand-edited (the
    `<!-- Generated by holoctl -->` header is missing). Pass `--force` to
    overwrite anyway. The exception is `CLAUDE.md`: hand-edited files there
    are preserved by renaming to `CLAUDE.local.md` instead of being skipped.
    """
    root = find_project_root()
    if not root:
        console.print("[red]No .holoctl/ found. Run `holoctl init` first.[/red]")
        raise typer.Exit(1)

    config = load_config(root)
    targets = [target] if target else config.get("targets", ["claude"])

    # Pass --force to the per-target compilers via env var so they can choose
    # to bypass drift protection. (Module function signatures are kept simple.)
    if force:
        os.environ["HOLOCTL_COMPILE_FORCE"] = "1"
    else:
        os.environ.pop("HOLOCTL_COMPILE_FORCE", None)

    for t in targets:
        try:
            result = compile_project(root, config, t, dry_run=dry_run)
            if dry_run:
                console.print(f"[dim][dry-run] {t}:[/dim]")
                for f in result["files"]:
                    console.print(f"  [dim]would write[/dim] {f}")
            else:
                console.print(f"[green]✓ {t}[/green] [dim]({len(result['files'])} files)[/dim]")
                for f in result["files"]:
                    console.print(f"  [dim]→[/dim] {f}")
                skipped = result.get("skipped") or []
                for s in skipped:
                    console.print(f"  [yellow]skipped[/yellow] {s['path']} [dim]({s['reason']})[/dim]")
        except ValueError as e:
            console.print(f"[red]✗ {t}: {e}[/red]")
