import fs from 'node:fs';
import path from 'node:path';
import { parseFrontmatter } from '../markdown.js';
import { resolveTemplate } from './template.js';

const HEADER = '<!-- Generated by projctl. Do not edit directly. Source: .projctl/ -->\n\n';

const MODEL_MAP = {
  fast: 'haiku',
  standard: 'sonnet',
  reasoning: 'opus',
};

const TOOL_MAP = {
  read: 'Read',
  search: 'Grep, Glob',
  edit: 'Edit',
  write: 'Write',
  shell: 'Bash',
  browser: 'WebSearch, WebFetch',
};

export function compileClaude(projectRoot, config, opts = {}) {
  const files = [];

  // Compile agents
  const agentsDir = path.join(projectRoot, '.projctl', 'agents');
  const claudeAgentsDir = path.join(projectRoot, '.claude', 'agents');

  if (fs.existsSync(agentsDir)) {
    if (!opts.dryRun) fs.mkdirSync(claudeAgentsDir, { recursive: true });

    for (const file of fs.readdirSync(agentsDir).filter(f => f.endsWith('.md'))) {
      const content = fs.readFileSync(path.join(agentsDir, file), 'utf8');
      const { data, body } = parseFrontmatter(content);

      const claudeFrontmatter = [
        '---',
        `name: ${data.name || file.replace('.md', '')}`,
        `description: ${data.description || ''}`,
        `tools: ${mapTools(data.tools)}`,
        `model: ${MODEL_MAP[data.model] || data.model || 'sonnet'}`,
        '---',
      ].join('\n');

      const resolvedBody = resolveTemplate(body, config);
      const output = HEADER + claudeFrontmatter + '\n' + resolvedBody;
      const outPath = `.claude/agents/${file}`;

      if (!opts.dryRun) {
        fs.writeFileSync(path.join(projectRoot, outPath), output, 'utf8');
      }
      files.push(outPath);
    }
  }

  // Compile commands
  const commandsDir = path.join(projectRoot, '.projctl', 'commands');
  const claudeCommandsDir = path.join(projectRoot, '.claude', 'commands');

  if (fs.existsSync(commandsDir)) {
    if (!opts.dryRun) fs.mkdirSync(claudeCommandsDir, { recursive: true });

    for (const file of fs.readdirSync(commandsDir).filter(f => f.endsWith('.md'))) {
      const content = fs.readFileSync(path.join(commandsDir, file), 'utf8');
      const resolved = resolveTemplate(content, config);
      const output = HEADER + resolved;
      const outPath = `.claude/commands/${file}`;

      if (!opts.dryRun) {
        fs.writeFileSync(path.join(projectRoot, outPath), output, 'utf8');
      }
      files.push(outPath);
    }
  }

  // Compile instructions → CLAUDE.md
  const instructionsPath = path.join(projectRoot, '.projctl', 'instructions.md');
  if (fs.existsSync(instructionsPath)) {
    const content = fs.readFileSync(instructionsPath, 'utf8');
    const resolved = resolveTemplate(content, config);
    const output = HEADER + resolved;
    const outPath = 'CLAUDE.md';

    if (!opts.dryRun) {
      fs.writeFileSync(path.join(projectRoot, outPath), output, 'utf8');
    }
    files.push(outPath);
  }

  return { files };
}

function mapTools(tools) {
  if (!tools) return 'Read, Grep, Glob, Edit, Write, Bash';
  const arr = Array.isArray(tools) ? tools : String(tools).split(',').map(s => s.trim());
  const mapped = arr.map(t => TOOL_MAP[t] || t).join(', ');
  return mapped;
}
