import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { resolveTemplate } from './template.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const HEADER = '<!-- Generated by projctl. Do not edit directly. Source: .projctl/ -->\n\n';

export function compileCopilot(projectRoot, config, opts = {}) {
  const files = [];
  const githubDir = path.join(projectRoot, '.github');

  // Bootstrap /projctl prompt → .github/prompts/projctl.prompt.md
  const tplPath = path.join(__dirname, '../../templates/commands/projctl-copilot.prompt.md');
  if (fs.existsSync(tplPath)) {
    const promptsDir = path.join(githubDir, 'prompts');
    if (!opts.dryRun) fs.mkdirSync(promptsDir, { recursive: true });
    const outPath = `.github/prompts/projctl.prompt.md`;
    if (!opts.dryRun) fs.writeFileSync(path.join(projectRoot, outPath), fs.readFileSync(tplPath, 'utf8'), 'utf8');
    files.push(outPath);
  }

  // Commands → .github/prompts/
  const commandsDir = path.join(projectRoot, '.projctl', 'commands');
  if (fs.existsSync(commandsDir)) {
    const promptsDir = path.join(githubDir, 'prompts');
    if (!opts.dryRun) fs.mkdirSync(promptsDir, { recursive: true });
    for (const file of fs.readdirSync(commandsDir).filter(f => f.endsWith('.md'))) {
      const baseName = file.replace(/\.md$/, '.prompt.md');
      const content = fs.readFileSync(path.join(commandsDir, file), 'utf8');
      const resolved = resolveTemplate(content, config);
      const outPath = `.github/prompts/${baseName}`;
      if (!opts.dryRun) fs.writeFileSync(path.join(projectRoot, outPath), resolved, 'utf8');
      files.push(outPath);
    }
  }

  // Instructions → .github/copilot-instructions.md
  const instructionsPath = path.join(projectRoot, '.projctl', 'instructions.md');
  if (fs.existsSync(instructionsPath)) {
    const content = fs.readFileSync(instructionsPath, 'utf8');
    const resolved = HEADER + resolveTemplate(content, config);
    const outPath = `.github/copilot-instructions.md`;
    if (!opts.dryRun) {
      fs.mkdirSync(githubDir, { recursive: true });
      fs.writeFileSync(path.join(projectRoot, outPath), resolved, 'utf8');
    }
    files.push(outPath);
  }

  return { files };
}
