import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseFrontmatter } from '../markdown.js';
import { resolveTemplate } from './template.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const HEADER = '<!-- Generated by holoctl. Do not edit directly. Source: .holoctl/ -->\n\n';

export function compileCursor(projectRoot, config, opts = {}) {
  const files = [];

  // Commands → .cursor/commands/
  const commandsDir = path.join(projectRoot, '.holoctl', 'commands');
  const outDir = path.join(projectRoot, '.cursor', 'commands');

  if (fs.existsSync(commandsDir)) {
    if (!opts.dryRun) fs.mkdirSync(outDir, { recursive: true });
    for (const file of fs.readdirSync(commandsDir).filter(f => f.endsWith('.md'))) {
      const content = fs.readFileSync(path.join(commandsDir, file), 'utf8');
      const resolved = HEADER + resolveTemplate(content, config);
      const outPath = `.cursor/commands/${file}`;
      if (!opts.dryRun) fs.writeFileSync(path.join(projectRoot, outPath), resolved, 'utf8');
      files.push(outPath);
    }
  }

  // Bootstrap /holoctl command
  const tplPath = path.join(__dirname, '../../templates/commands/holoctl-cursor.md');
  if (fs.existsSync(tplPath)) {
    const outPath = `.cursor/commands/holoctl.md`;
    if (!opts.dryRun) {
      fs.mkdirSync(path.join(projectRoot, '.cursor', 'commands'), { recursive: true });
      fs.writeFileSync(path.join(projectRoot, outPath), fs.readFileSync(tplPath, 'utf8'), 'utf8');
    }
    files.push(outPath);
  }

  // Instructions → .cursor/rules/holoctl.md
  const instructionsPath = path.join(projectRoot, '.holoctl', 'instructions.md');
  if (fs.existsSync(instructionsPath)) {
    const content = fs.readFileSync(instructionsPath, 'utf8');
    const resolved = HEADER + resolveTemplate(content, config);
    const outPath = `.cursor/rules/holoctl.md`;
    if (!opts.dryRun) {
      fs.mkdirSync(path.join(projectRoot, '.cursor', 'rules'), { recursive: true });
      fs.writeFileSync(path.join(projectRoot, outPath), resolved, 'utf8');
    }
    files.push(outPath);
  }

  return { files };
}
