import fs from 'node:fs';
import path from 'node:path';
import { parseFrontmatter } from '../markdown.js';
import { resolveTemplate } from './template.js';

const HEADER = '<!-- Generated by holoctl. Do not edit directly. Source: .holoctl/ -->\n\n';

export function compileGeneric(projectRoot, config, opts = {}) {
  const files = [];

  // AGENTS.md — concatenated agents
  const agentsDir = path.join(projectRoot, '.holoctl', 'agents');
  if (fs.existsSync(agentsDir)) {
    const agentFiles = fs.readdirSync(agentsDir).filter(f => f.endsWith('.md'));
    let agentsMd = HEADER + '# Agents\n\n';

    for (const file of agentFiles) {
      const content = fs.readFileSync(path.join(agentsDir, file), 'utf8');
      const { data, body } = parseFrontmatter(content);
      const resolved = resolveTemplate(body, config);
      agentsMd += `## ${data.name || file.replace('.md', '')}\n\n`;
      agentsMd += `- **Model**: ${data.model || 'standard'}\n`;
      agentsMd += `- **Trigger**: ${data.trigger || 'ticket'}\n`;
      if (data.description) agentsMd += `- **Description**: ${data.description}\n`;
      agentsMd += '\n' + resolved + '\n---\n\n';
    }

    const outPath = 'AGENTS.md';
    if (!opts.dryRun) {
      fs.writeFileSync(path.join(projectRoot, outPath), agentsMd, 'utf8');
    }
    files.push(outPath);
  }

  // COMMANDS.md — concatenated commands
  const commandsDir = path.join(projectRoot, '.holoctl', 'commands');
  if (fs.existsSync(commandsDir)) {
    const cmdFiles = fs.readdirSync(commandsDir).filter(f => f.endsWith('.md'));
    let commandsMd = HEADER + '# Commands\n\n';

    for (const file of cmdFiles) {
      const content = fs.readFileSync(path.join(commandsDir, file), 'utf8');
      const resolved = resolveTemplate(content, config);
      commandsMd += resolved + '\n---\n\n';
    }

    const outPath = 'COMMANDS.md';
    if (!opts.dryRun) {
      fs.writeFileSync(path.join(projectRoot, outPath), commandsMd, 'utf8');
    }
    files.push(outPath);
  }

  // AI-INSTRUCTIONS.md — instructions file
  const instructionsPath = path.join(projectRoot, '.holoctl', 'instructions.md');
  if (fs.existsSync(instructionsPath)) {
    const content = fs.readFileSync(instructionsPath, 'utf8');
    const resolved = resolveTemplate(content, config);
    const outPath = 'AI-INSTRUCTIONS.md';
    if (!opts.dryRun) {
      fs.writeFileSync(path.join(projectRoot, outPath), HEADER + resolved, 'utf8');
    }
    files.push(outPath);
  }

  return { files };
}
