import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { resolveTemplate } from './template.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const HEADER = '<!-- Generated by projctl. Do not edit directly. Source: .projctl/ -->\n\n';

export function compileWindsurf(projectRoot, config, opts = {}) {
  const files = [];

  // Commands → .windsurf/workflows/
  const commandsDir = path.join(projectRoot, '.projctl', 'commands');
  const outDir = path.join(projectRoot, '.windsurf', 'workflows');

  if (fs.existsSync(commandsDir)) {
    if (!opts.dryRun) fs.mkdirSync(outDir, { recursive: true });
    for (const file of fs.readdirSync(commandsDir).filter(f => f.endsWith('.md'))) {
      const content = fs.readFileSync(path.join(commandsDir, file), 'utf8');
      const resolved = resolveTemplate(content, config);
      const outPath = `.windsurf/workflows/${file}`;
      if (!opts.dryRun) fs.writeFileSync(path.join(projectRoot, outPath), resolved, 'utf8');
      files.push(outPath);
    }
  }

  // Bootstrap /projctl workflow
  const tplPath = path.join(__dirname, '../../templates/commands/projctl-windsurf.md');
  if (fs.existsSync(tplPath)) {
    if (!opts.dryRun) fs.mkdirSync(path.join(projectRoot, '.windsurf', 'workflows'), { recursive: true });
    const outPath = `.windsurf/workflows/projctl.md`;
    if (!opts.dryRun) fs.writeFileSync(path.join(projectRoot, outPath), fs.readFileSync(tplPath, 'utf8'), 'utf8');
    files.push(outPath);
  }

  // Instructions → .windsurfrules
  const instructionsPath = path.join(projectRoot, '.projctl', 'instructions.md');
  if (fs.existsSync(instructionsPath)) {
    const content = fs.readFileSync(instructionsPath, 'utf8');
    const resolved = HEADER + resolveTemplate(content, config);
    const outPath = `.windsurfrules`;
    if (!opts.dryRun) fs.writeFileSync(path.join(projectRoot, outPath), resolved, 'utf8');
    files.push(outPath);
  }

  return { files };
}
